// Reports Catalogue (M63) — GENERATED by mk-catalogue.js from catalogue-index.json and the families. Do not edit: change those, then npm run gen.
MK.app({
  title: 'Reports Catalogue', primary: 'company_files', files: 'company_files',
  inputs: { companyFile: 'company_file', persona: 'persona', display: 'display' },
  defaults: { company_file: '', persona: 'Client',
    display: '{"cents":1,"k":0,"zeros":1,"neg":"paren","red":0,"hdr":1,"ftr":1,"style":"myob","dens":"100","p":"custom","a":"custom","c":"none","v":"all","x":""}' },
  uses: { company_files: [] },
  tools: { company_files: 'list_company_files (the client selector)' },
  catalogue: {"total": 64, "groups": [["Business","Business","Business reports",14],["Banking","Banking","Banking reports",5],["Payroll","Payroll","Payroll reports",12],["Sales","Sales","Sales reports",8],["Purchases","Purchases","Purchases reports",7],["Inventory","Inventory","Inventory reports",6],["Jobs","Jobs","Jobs reports",6],["More","More","More reporting",null]], "rows": [
{"m":"M00","name":"Dashboard","group":"More","status":"live","ask":"Ask for “MYOB Dashboard”","desc":"Home dashboard: 'Up next' tasks, Your business (Income / Expenses / Financial position), Accounts (bank balance / money owed), GST to pay, Overdue invoices by age, Pay runs, Superannuation payable, Uploads, PAYG withholding."},
{"m":"M01","name":"Budget management","group":"Business","status":"request","ask":"Ask for “MYOB Budget Management”","desc":"Set up budgets to predict and track your business performance."},
{"m":"M02","name":"Balance sheet","group":"Business","status":"live","ask":"Ask for “MYOB Balance Sheet”","desc":"A snapshot of the balances in your asset, liability and equity accounts as at a specified date."},
{"m":"M03","name":"Trial balance","group":"Business","status":"live","ask":"Ask for “MYOB Trial Balance”","desc":"All your categories debit and credit activity within a specified date range including year-to-date balances."},
{"m":"M04","name":"Profit and loss","group":"Business","status":"live","ask":"Ask for “MYOB Profit and Loss”","desc":"A summary of income and expenses within a specified date range. Compare to budget and last year's figures."},
{"m":"M05","name":"Cash movement","group":"Business","status":"live","ask":"Ask for “MYOB Cash Movement”","desc":"All movements of cash in and out of your business within a specified date range."},
{"m":"M06","name":"GST report","group":"Business","status":"live","ask":"Ask for “MYOB GST Summary (BAS)”","desc":"Detailed GST information that you can use to prepare your BAS or GST return."},
{"m":"M07","name":"GST return","group":"Business","status":"live","ask":"Part of “MYOB GST Summary (BAS)”","desc":"A summary of GST for your Activity Statement."},
{"m":"M08","name":"General ledger","group":"Business","status":"live","ask":"Ask for “MYOB General Ledger”","desc":"A list of all transactions grouped by account within a specified date range."},
{"m":"M09","name":"Journal entries","group":"Business","status":"live","ask":"Ask for “MYOB Journal Entries”","desc":"All the transactions within a specified date range in the form of journal entries."},
{"m":"M10","name":"Categories list","group":"Business","status":"live","ask":"Ask for “MYOB Categories List”","desc":"A list of categories with their balances as at a specified date."},
{"m":"M11","name":"Categories transactions","group":"Business","status":"live","ask":"Ask for “MYOB Categories Transactions”","desc":"Displays either the debit or credit side of any transactions attached to the selected categories. It does not display the entire transactions."},
{"m":"M12","name":"Contacts","group":"Business","status":"live","ask":"Ask for “MYOB Contacts”","desc":"A list of contacts including phone, email, and other details."},
{"m":"M13","name":"Journal security audit","group":"Business","status":"export","ask":"Attach the MYOB export, then ask for “MYOB Journal Security Audit”","desc":"A list of all changes made to transactions."},
{"m":"M14","name":"Taxable payments annual report","group":"Business","status":"request","ask":"Ask for “MYOB Taxable Payments Annual Report”","desc":"A report required by the ATO for a growing number of businesses that make payments to contractors for services."},
{"m":"M15","name":"Bank activity","group":"Banking","status":"live","ask":"Ask for “MYOB Bank Activity”","desc":"All bank and credit card transactions within a specified date range, plus a running account balance."},
{"m":"M16","name":"Bank transactions","group":"Banking","status":"live","ask":"Ask for “MYOB Bank Transactions”","desc":"Deposits and withdrawals from bank feeds or imported statements, plus a running account balance. These are the same transactions that appear on the bank transaction page."},
{"m":"M17","name":"Banking reconciliation","group":"Banking","status":"live","ask":"Ask for “MYOB Bank Reconciliation Status”","desc":"A summary or detail of each bank reconciliation you've completed."},
{"m":"M18","name":"Coding","group":"Banking","status":"live","ask":"Ask for “MYOB Coding”","desc":"A list of bank transactions within a specified date range that are categorised or uncategorised."},
{"m":"M19","name":"Statement of cash flow","group":"Banking","status":"live","ask":"Ask for “MYOB Statement of Cash Flows”","desc":"Reports changes in cash and cash equivalents for a given period."},
{"m":"M20","name":"Payroll summary","group":"Payroll","status":"live","ask":"Ask for “MYOB Payroll Summary”","desc":"A summary displaying total values for salary and wages, taxes, deductions, leave, and expenses."},
{"m":"M21","name":"Payroll register","group":"Payroll","status":"live","ask":"Ask for “MYOB Payroll Register”","desc":"A list of salary and wages, taxes, deductions, leave, and expenses for selected employees."},
{"m":"M22","name":"Payroll activity","group":"Payroll","status":"live","ask":"Part of “MYOB Payroll Register”","desc":"A detailed list of salary and wages, taxes, deductions, leave, and expenses for selected employees."},
{"m":"M23","name":"Pay run history","group":"Payroll","status":"live","ask":"Ask for “MYOB Pay Run History”","desc":"Pay run details by employee within a specified payment date range or using a selected pay run date."},
{"m":"M24","name":"Timesheets","group":"Payroll","status":"live","ask":"Ask for “MYOB Timesheets”","desc":"Timesheets for each of your employees."},
{"m":"M25","name":"Accrual by fund","group":"Payroll","status":"live","ask":"Ask for “MYOB Accrual by Fund”","desc":"Summary of superannuation contributions created from pay runs within a specified date range."},
{"m":"M26","name":"Accrual by fund (detail)","group":"Payroll","status":"live","ask":"Part of “MYOB Accrual by Fund”","desc":"Detail of superannuation contributions created from pay runs within a specified date range."},
{"m":"M27","name":"Superannuation payments","group":"Payroll","status":"live","ask":"Ask for “MYOB Superannuation Payments”","desc":"Details of Pay Super payments with a comparison to super accrued by employee for a specified period."},
{"m":"M28","name":"Leave balance","group":"Payroll","status":"live","ask":"Ask for “MYOB Leave Balance”","desc":"Total available hours, hours taken, and hours accrued for each employee within a specified date range."},
{"m":"M29","name":"Leave balance (detail)","group":"Payroll","status":"live","ask":"Part of “MYOB Leave Balance”","desc":"A running balance of available hours, hours taken, and hours accrued for each employee within a specified date range."},
{"m":"M30","name":"Pay item transactions","group":"Payroll","status":"live","ask":"Ask for “MYOB Pay Item Transactions”","desc":"A list of all transactions grouped by pay item."},
{"m":"M31","name":"Workers compensation — Estimation of wages","group":"Payroll","status":"export","ask":"Attach the MYOB export, then ask for “MYOB Workers Compensation”","desc":"Estimate wages for your workers compensation (new)."},
{"m":"M32","name":"Unpaid invoices","group":"Sales","status":"live","ask":"Ask for “MYOB Unpaid Invoices” or “MYOB Aged Receivables”","desc":"Current balance of invoices issued up to a specified date with ageing details for each customer."},
{"m":"M33","name":"Receivables reconciliation with tax","group":"Sales","status":"live","ask":"Ask for “MYOB Receivables Reconciliation”","desc":"A list of receivables as at a specified date with tax, ageing details and a comparison to the receivables linked category balance."},
{"m":"M34","name":"Receivables reconciliation exceptions","group":"Sales","status":"live","ask":"Ask for “MYOB Receivables Reconciliation”","desc":"Compares the total balance of your customers' outstanding invoices to the current balance of the linked receivables category."},
{"m":"M35","name":"Customer sales","group":"Sales","status":"live","ask":"Ask for “MYOB Customer Sales”","desc":"All invoices within the specified date range."},
{"m":"M36","name":"Customer sales (detail)","group":"Sales","status":"live","ask":"Ask for “MYOB Customer Sales (Detail)”","desc":"Detailed information for all invoices within the specified date range."},
{"m":"M37","name":"Customer transactions","group":"Sales","status":"live","ask":"Ask for “MYOB Customer Transactions”","desc":"All invoices, payments and credits within the specified date range."},
{"m":"M38","name":"Sales register","group":"Sales","status":"live","ask":"Ask for “MYOB Sales Register”","desc":"All quotes, orders and invoices within the specified date range."},
{"m":"M39","name":"Item sales","group":"Sales","status":"live","ask":"Ask for “MYOB Item Sales”","desc":"Sales information for each of your items."},
{"m":"M40","name":"Unpaid bills","group":"Purchases","status":"live","ask":"Ask for “MYOB Unpaid Bills” or “MYOB Aged Payables”","desc":"Current balance of bills issued up to a specified date with ageing details for each supplier."},
{"m":"M41","name":"Payables reconciliation with tax","group":"Purchases","status":"live","ask":"Ask for “MYOB Payables Reconciliation”","desc":"A list of payables as at a specified date with tax, ageing details and a comparison to the payables linked category balance."},
{"m":"M42","name":"Payables reconciliation exceptions","group":"Purchases","status":"live","ask":"Ask for “MYOB Payables Reconciliation”","desc":"Compares the total balance of your unpaid bills to the balance of your linked payables category."},
{"m":"M43","name":"Supplier purchases","group":"Purchases","status":"live","ask":"Ask for “MYOB Supplier Purchases”","desc":"All bills within the specified date range."},
{"m":"M44","name":"Supplier purchases (detail)","group":"Purchases","status":"live","ask":"Ask for “MYOB Supplier Purchases (Detail)”","desc":"Detailed information for all bills within the specified date range."},
{"m":"M45","name":"Supplier transactions","group":"Purchases","status":"live","ask":"Ask for “MYOB Supplier Transactions”","desc":"All bills, payments and debits within the specified date range."},
{"m":"M46","name":"Purchase register","group":"Purchases","status":"live","ask":"Ask for “MYOB Purchase Register”","desc":"All quotes, orders and bills within the specified date range."},
{"m":"M47","name":"Reorder","group":"Inventory","status":"request","ask":"Ask for “MYOB Reorder”","desc":"A list of your items to be reordered based upon your minimum stock levels."},
{"m":"M48","name":"Stock on hand","group":"Inventory","status":"request","ask":"Ask for “MYOB Stock on Hand”","desc":"Displays current stock level quantities, and inventoried items committed and on order."},
{"m":"M49","name":"Item sales analysis","group":"Inventory","status":"live","ask":"Ask for “MYOB Item Sales Analysis”","desc":"Analyse your items' sales performance over time."},
{"m":"M50","name":"Items register","group":"Inventory","status":"request","ask":"Ask for “MYOB Items Register”","desc":"A detailed list of transactions for inventory items."},
{"m":"M51","name":"Item list","group":"Inventory","status":"request","ask":"Ask for “MYOB Item List”","desc":"A list of your items with item information."},
{"m":"M52","name":"Inventory value reconciliation","group":"Inventory","status":"request","ask":"Ask for “MYOB Inventory Value Reconciliation”","desc":"Compares the total value of all on-hand inventory to the current balance of the linked inventory categories."},
{"m":"M53","name":"Job profit and loss","group":"Jobs","status":"request","ask":"Ask for “MYOB Job Profit and Loss”","desc":"Displays a P&L report totalling the transactions assigned to selected jobs."},
{"m":"M54","name":"Job profit and loss comparison","group":"Jobs","status":"request","ask":"Ask for “MYOB Job Profit and Loss Comparison”","desc":"Displays a side-by-side P&L report totalling the transactions assigned to selected jobs."},
{"m":"M55","name":"Job transactions (accrual)","group":"Jobs","status":"request","ask":"Ask for “MYOB Job Transactions”","desc":"Display all transactions that have been assigned to a job."},
{"m":"M56","name":"Job activity","group":"Jobs","status":"request","ask":"Ask for “MYOB Job Activity”","desc":"Displays every transaction assigned to a job within the given date range for each selected account."},
{"m":"M57","name":"Job exceptions (cash transactions)","group":"Jobs","status":"request","ask":"Ask for “MYOB Job Exceptions”","desc":"Displays a list of all spend money, receive money, inventory and general journal transactions lines that have not been assigned to a job."},
{"m":"M58","name":"Job exceptions (invoice transactions)","group":"Jobs","status":"request","ask":"Ask for “MYOB Job Exceptions”","desc":"Displays a list of all sales and purchase transactions that have not been assigned to a job."},
{"m":"M59","name":"Exceptions dashboard","group":"More","status":"live","ask":"Ask for “MYOB Exceptions Dashboard”","desc":"Transaction review and Tax review checks over a period, run on demand ('Run review')."},
{"m":"M60","name":"Report packs — Management Report","group":"More","status":"live","ask":"Ask for “MYOB Report Pack”","desc":"Templates (MYOB 'Management Report': a set of key financial reports used for monitoring the performance of your business) and generated Report Packs."},
{"m":"M61","name":"BAS report (Activity Statement)","group":"More","status":"live","ask":"Part of “MYOB GST Summary (BAS)”","desc":"BAS reports created per period (Financial year filter; 'Create new BAS report'). None existed in the sample file."},
{"m":"M62","name":"Custom report (user-defined columns and filters)","group":"More","status":"guide","ask":"Ask to save any report with your settings (“MYOB Custom Reports”)","desc":"You can create reports with your preferred filters and columns. Select the customise button in reports to get started."},
{"m":"M63","name":"Reports catalogue and runner (All tab)","group":"More","status":"live","ask":"Ask for “MYOB Reports Catalogue”","desc":"Reports home: tabs All · Business · Banking · Payroll (New report) · Sales · Purchases · Inventory · Jobs; search; favourites star per report; 58 reports with one-line descriptions."}
]},
  render: function (c) {
    var K = this.catalogue, h = MK.h, body = c.body, self = this;
    var TABS = [['all', 'All']].concat(K.groups.map(function (g) { return [g[0], g[1]]; })).concat([['fav', '★ Favourites']]);
    var tab = TABS.some(function (t) { return t[0] === c.display.v; }) ? c.display.v : 'all';
    var fav = String(c.display.x || '').split(',').filter(function (m) { return K.rows.some(function (r) { return r.m === m; }); });
    var STATUS = { live: ['Live template', 'live'], request: ['On request', 'req'], export: ['From your MYOB export', 'exp'], guide: ['Guide', 'exp'], none: ['Not yet', 'off'] };
    var count = function (s) { return K.rows.filter(function (r) { return r.status === s; }).length; };
    var card = function (r) {
      var st = STATUS[r.status] || STATUS.none, on = fav.indexOf(r.m) >= 0;
      return '<div class="ct-card' + (r.status === 'none' ? ' off' : '') + '" data-text="' + h((r.name + ' ' + r.desc + ' ' + r.m + ' ' + (r.ask || '')).toLowerCase()) + '">' +
        '<div class="ct-top"><span class="ct-name">' + h(r.name) + '</span><button type="button" class="ct-star' + (on ? ' on' : '') + '" data-m="' + h(r.m) + '" aria-pressed="' + on + '" title="' + (on ? 'Remove from favourites' : 'Add to favourites') + '">' + (on ? '★' : '☆') + '</button></div>' +
        '<div class="ct-desc">' + h(r.desc) + '</div>' + (r.ask ? '<div class="ct-ask">' + h(r.ask) + '</div>' : '') +
        '<div class="ct-foot"><span class="ct-badge ' + st[1] + '">' + st[0] + '</span><span class="muted">' + h(r.m) + '</span></div></div>';
    };
    var groups = K.groups.filter(function (g) { return tab === 'all' || tab === 'fav' || tab === g[0]; });
    var sections = groups.map(function (g) {
      var rows = K.rows.filter(function (r) { return r.group === g[0] && (tab !== 'fav' || fav.indexOf(r.m) >= 0); });
      return rows.length ? '<section class="ct-sec"><h2>' + h(g[2]) + '</h2><div class="ct-grid">' + rows.map(card).join('') + '</div></section>' : '';
    }).join('');
    body.innerHTML = '<style>.ct-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:12px}.ct-sec h2{font-size:16px;margin:20px 0 10px}' +
      '.ct-card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:12px 14px;display:flex;flex-direction:column;gap:6px}.ct-card.off{opacity:.55}' +
      '.ct-top{display:flex;justify-content:space-between;gap:8px}.ct-name{font-weight:700;color:var(--accent)}.ct-desc{font-size:13px;color:var(--muted);flex:1}.ct-ask{font-size:12px}' +
      '.ct-foot{display:flex;justify-content:space-between;align-items:center;font-size:11px}.ct-badge{font-weight:700;border-radius:10px;padding:2px 8px;background:var(--line);color:var(--muted)}' +
      '.ct-badge.live{background:var(--pass-bg);color:var(--pos)}.ct-badge.req{color:var(--accent)}.ct-star{font:inherit;font-size:18px;line-height:1;background:none;border:0;color:var(--accent);cursor:pointer;padding:0}' +
      '.ct-tabs{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.ct-tab{font:inherit;font-size:13px;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:16px;padding:5px 14px;cursor:pointer}' +
      '.ct-tab.on{background:var(--accent);border-color:var(--accent);color:var(--btn-ink)}</style>' +
      MK.kpis([{ label: 'Reports in the library', money: false, value: K.rows.length }, { label: 'Live templates', money: false, value: count('live') }, { label: 'On request', money: false, value: count('request') },
        { label: 'From an export or a guide', money: false, value: count('export') + count('guide') }, { label: 'Favourites', money: false, value: fav.length }], c) +
      '<input id="ct-q" type="search" class="mk-filter" style="width:100%;margin-top:12px" placeholder="Search reports" aria-label="Search reports" value="' + h(self._q || '') + '">' +
      '<div class="ct-tabs" role="tablist">' + TABS.map(function (t) { return '<button type="button" role="tab" class="ct-tab' + (t[0] === tab ? ' on' : '') + '" data-tab="' + t[0] + '" aria-selected="' + (t[0] === tab) + '">' + h(t[1]) + '</button>'; }).join('') + '</div>' +
      '<div id="ct-sections">' + (sections || '<p class="muted">' + (tab === 'fav' ? 'No favourites yet — press ☆ on a report.' : 'No reports in this tab.') + '</p>') + '</div><p id="ct-none" class="muted" hidden>No reports match the search.</p>';
    function filter() {
      var q = (self._q || '').trim().toLowerCase(), any = false;
      body.querySelectorAll('.ct-sec').forEach(function (s) { var n = 0; s.querySelectorAll('.ct-card').forEach(function (cd) { var okq = !q || cd.getAttribute('data-text').indexOf(q) >= 0; cd.hidden = !okq; if (okq) n++; }); s.hidden = !n; if (n) any = true; });
      var none = document.getElementById('ct-none'); if (none) none.hidden = any || !body.querySelector('.ct-sec');
    }
    var qi = document.getElementById('ct-q'); qi.addEventListener('input', function () { self._q = qi.value; filter(); }); filter();
    body.querySelectorAll('.ct-tab').forEach(function (b) { b.addEventListener('click', function () { c.change({}, { v: b.getAttribute('data-tab') }); }); });
    body.querySelectorAll('.ct-star').forEach(function (b) { b.addEventListener('click', function () { var m = b.getAttribute('data-m'), i = fav.indexOf(m), f = fav.slice(); if (i >= 0) f.splice(i, 1); else f.push(m); c.change({}, { x: f.join(',') }); }); });
    var ids = K.rows.map(function (r) { return r.m; }), uniq = ids.filter(function (m, i) { return ids.indexOf(m) === i && /^M\d\d$/.test(m); });
    var byGroup = {}; K.rows.forEach(function (r) { byGroup[r.group] = (byGroup[r.group] || 0) + 1; });
    var tabsOk = K.groups.every(function (g) { return g[3] == null || byGroup[g[0]] === g[3]; });
    this._x = { rows: K.rows, STATUS: STATUS, fav: fav };
    return { checks: [
      { name: 'Every report maps to a prompt ID in this library (M00–M63)', pass: uniq.length === K.total && ids.length === K.total, detail: uniq.length + ' of ' + K.total + ' prompt IDs' },
      { name: 'Reports per MYOB tab match MYOB (Business 14 · Banking 5 · Payroll 12 · Sales 8 · Purchases 7 · Inventory 6 · Jobs 6)', pass: tabsOk, detail: K.groups.map(function (g) { return g[1] + ' ' + (byGroup[g[0]] || 0); }).join(' · ') },
      { name: 'Coverage', pass: null, info: true, detail: count('live') + ' live templates · ' + count('request') + ' on request · ' + count('export') + ' from an export · ' + count('guide') + ' guide' + (count('none') ? ' · ' + count('none') + ' not yet' : '') }],
      title: 'Reports Catalogue', period: K.total + ' reports · MYOB Reports Prompt Library v1.2',
      notes: ['Live template = a tested report the agent creates from its template; ask for it by the name shown. On request = the agent writes the report from its specification each time. From your MYOB export = MYOB\'s API does not expose it: attach the MYOB export and ask for it. Prompt IDs refer to the MYOB Reports Prompt Library v1.2.',
        'Stars last while this catalogue is open and go into its downloads. To keep favourites, ask the agent to save the catalogue with them.'] };
  },
  excel: function (c) {
    var x = this._x; if (!x) return [];
    var G = {}; this.catalogue.groups.forEach(function (g) { G[g[0]] = g[1]; });
    return [{ name: 'Reports catalogue', widths: [14, 36, 8, 22, 40, 90, 10], rows: [[{ v: c.company || 'N/A — not in source', s: 'title' }], [{ v: 'Reports Catalogue', s: 'bold' }], [],
      [{ v: 'Tab', s: 'bold' }, { v: 'Report', s: 'bold' }, { v: 'Prompt ID', s: 'bold' }, { v: 'Status', s: 'bold' }, { v: 'Ask for', s: 'bold' }, { v: 'Description', s: 'bold' }, { v: 'Favourite', s: 'bold' }]]
      .concat(x.rows.map(function (r) { return [G[r.group] || r.group, r.name, r.m, (x.STATUS[r.status] || x.STATUS.none)[0], r.ask || '', r.desc, x.fav.indexOf(r.m) >= 0 ? '★' : '']; })) }];
  }
});
