// MYOB Reports Prompt Library v1.2 families built on the tested kit. Each writes skills/<skill>.md (existing file stems, so the
// agent blueprint's skill ids do not change). Reports not listed here keep their prose skills.
module.exports = [
  {
    m: 'M04', skill: 'profit-and-loss', name: 'MYOB Profit and Loss', report: 'pnl', wave: 'Wave 1 (P1, delivery order 1)',
    title: 'Profit and loss', menu: 'Reporting → Reports → Business → Profit and loss',
    trigger: 'the user asks for a profit and loss, P&L, income statement, trading statement, net profit, income and expenses for a period, or a P&L comparison with last year',
    discovery: 'Call `get_profit_and_loss_3m` once with `from_date` = the financial-year start, `to_date` = today and `reporting_basis` = `Accrual`, and call `list_company_files` once. Expect `{StartDate, EndDate, ReportingBasis, AccountsBreakdown:[{Account:{UID,Name,DisplayID}, AccountTotal}]}` — one total per account and **no section totals** (the kit classifies each account with `list_accounts` and adds them up). An empty `AccountsBreakdown` means no activity, not an error. `{"__error": …}` is a failed call',
    dates: '`from_date` = start of the period asked for (default: financial-year start, e.g. `2026-07-01`); `to_date` = end of the period (default `"today"`). Set the display preset `p` to match (`this_fy_td` by default; `this_month`, `last_month`, `this_quarter`, `last_quarter`, `last_fy` or `custom`). Comparison dates are set by the kit from the Compare to control; leave their defaults.',
    members: [['Profit and loss', 'Report = Profit and Loss (default)'], ['Profit and loss as % of income', 'Report = P&L as % of income'], ['Profit and loss comparison', 'Compare to = Previous period / Previous year / Year to date (adds comparison, $ change and % change columns)'], ['Cash basis', 'Accounting method = Cash'], ['Breakdown by month / category / job', 'N/A — the MYOB API P&L summary returns one total per account (say so; offer the total view)']],
    checks: ['Every account on the P&L is classified (Income, Cost of Sales, Expense, Other Income, Other Expense from the chart of accounts)', 'Section totals = Σ their accounts', 'Gross Profit = Income − Cost of Sales; Net Profit = Gross Profit − Expenses + Other Income − Other Expenses', '**Independent tie:** for a financial-year-to-date range, Net Profit = Current Year Earnings on the Balance Sheet at the end date (a separate MYOB report); other ranges show this as information', 'Comparison period loaded (when Compare to is on)'],
    golden: 'mySMB.com, 1 Jul – 9 Sep 2026 accrual: Sales / Total income / Gross profit 2,115.43; Electricity & Gas 290.91; Office Supplies 132.27; Telephone & Internet 81.77; Total expenses 504.95; Net profit 1,610.48; last year 0.00. Live on 28 Sep 2026 (FY to date): Income 4,317.25, Expenses 2,134.49, Net profit 2,182.76',
    fileName: 'myob-profit-and-loss.html', tags: ['myob', 'profit-and-loss', 'M04', 'financial-statement'],
  },
  {
    m: 'M02', skill: 'balance-sheet', name: 'MYOB Balance Sheet', report: 'bs', wave: 'Wave 1 (P1, delivery order 2)',
    title: 'Balance sheet', menu: 'Reporting → Reports → Business → Balance sheet',
    trigger: 'the user asks for a balance sheet, statement of financial position, net assets, assets and liabilities as at a date, or a balance sheet comparison',
    discovery: 'Call `get_balance_sheet` once with `date` = today and `reporting_basis` = `Accrual`, and call `list_company_files` once. Expect `{AsOfDate, AccountsBreakdown:[{Account:{UID,Name,DisplayID}, AccountTotal}]}` — no totals; values are positive in each account\'s normal balance (an overdrawn bank is negative). The Equity section includes MYOB\'s Current Year Earnings account (this year\'s profit to date). `{"__error": …}` is a failed call',
    dates: '`as_at` = the balance date asked for (default `"today"`); set the display preset `a` to `today`, `end_last_month`, `end_last_quarter`, `end_last_fy` or `custom` to match. `fy_start` is derived by the kit from `as_at` — leave its default. `compare_as_at` is set by the Compare to control.',
    members: [['Balance sheet', 'Report = Balance Sheet (default)'], ['Balance sheet summary', 'Report = Summary (totals only)'], ['Comparison with last year / last month end', 'Compare to = Previous year / Previous month end'], ['Category levels 1–4, Consolidate', 'N/A — the MYOB API returns account totals only (header groupings are not reported); one company file per report']],
    checks: ["Total Assets = Total Liabilities + Total Equity. If they differ by exactly last financial year's net profit (a file not yet rolled over — MYOB's account summary then omits it), the report adds a computed equity line \"Prior year earnings not yet closed to Retained Earnings\" and an information line to roll over the year; any other difference fails and shows last year's profit for diagnosis", 'Every account on the Balance Sheet is classified', 'Section totals = Σ their accounts', '**Independent tie:** Current Year Earnings = P&L Net Profit from the financial-year start to the as-at date (a separate MYOB report)', 'Comparison date loaded (when Compare to is on)'],
    golden: 'mySMB.com as at 9 Sep 2026: Bank (555.45); Accounts receivable 2,326.96; Total assets 1,771.51; GST 161.03; Total liabilities 161.03; Net assets / Current year earnings / Total equity 1,610.48. Live on 28 Sep 2026: Total assets 3,896.01 (receivables 4,328.96, bank (432.95)), Total liabilities 1,713.25, Total equity 2,182.76',
    fileName: 'myob-balance-sheet.html', tags: ['myob', 'balance-sheet', 'M02', 'financial-statement'],
  },
  {
    m: 'M03', skill: 'trial-balance', name: 'MYOB Trial Balance', report: 'tb', wave: 'Wave 1 (P1, delivery order 12)',
    title: 'Trial balance', menu: 'Reporting → Reports → Business → Trial balance',
    trigger: 'the user asks for a trial balance, TB, debits and credits by account, or every category\'s balance as at a date',
    discovery: 'Call `get_balance_sheet` once with `date` = today and `reporting_basis` = `Accrual`, and `list_company_files` once. MYOB\'s API has no trial balance report: the report takes balance-sheet accounts from the Balance Sheet at the date and income and expense accounts from the Profit and Loss for the financial year to that date. A `{"__error": …}` result is a failed call: report its message',
    dates: '`as_at` = the balance date (default `"today"`; display preset `a` = `today`, `end_last_month`, `end_last_quarter`, `end_last_fy` or `custom`). `fy_start` and `prev_fy_start` are derived by the kit — leave them. For a cash-basis request set `basis` to `Cash`. The view is display `v` (`tb` | `class`).',
    members: [['Trial balance', 'Every category with its debit or credit balance as at the date (balance-sheet categories at the date, income and expense year to date)'], ['By classification', 'Report = By classification (debit and credit totals per classification)'], ['Activity columns for a date range', 'See the General ledger (MYOB\'s trial balance activity detail is not in the API)']],
    checks: ['Total debits = total credits (balance-sheet accounts at the date + income and expense accounts year to date — two MYOB reports); last financial year\'s profit not yet closed is shown as its own line when it is exactly the difference', '**Independent tie:** Current Year Earnings on the Balance Sheet = net profit for the financial year to date', 'Every account is classified (chart of accounts)'],
    golden: 'mySMB.com, September 2026: 1-1110 Business Bank Account #1 credit 555.45 · 1-1200 Accounts Receivable debit 2,326.96 · GST credit 161.03 · 4-1400 Sales credit 2,115.43 · 6-1430 Electricity & Gas 290.91; debits = credits',
    fileName: 'myob-trial-balance.html', tags: ['myob', 'trial-balance', 'M03', 'financial-statement'],
  },
  {
    m: 'M32', skill: 'unpaid-invoices', name: 'MYOB Unpaid Invoices', report: 'ar', wave: 'Wave 1 (P1, delivery order 4)',
    title: 'Unpaid invoices', menu: 'Reporting → Reports → Sales → Unpaid invoices',
    trigger: 'the user asks for unpaid invoices, who owes them money, outstanding sales invoices, a chase list, or receivables by customer with ageing',
    discovery: 'Call `list_invoices` once with `status` = `Open`, and `list_company_files` once. Expect `{Count, Items:[{Number, Date, Customer{Name, DisplayID, UID}, BalanceDueAmount, TotalAmount, TotalTax, Terms{DueDate}, Status}]}`. A `{"__error": …}` result is a failed call: report its message',
    dates: 'Always as at today — MYOB\'s API gives today\'s open balances (the kit sets `as_at`; leave it). The ageing method is `method` (`Invoice date` — MYOB\'s default — or `Due date`). The view is display `v` (`customers` | `invoices`).',
    members: [['Unpaid invoices', 'Customer name | Customer number | 0 - 30 | 31 - 60 | 61 - 90 | 90+ | Total due, one row per customer, totals row'], ['Invoices', 'Report = Invoices (each open invoice with its age)'], ['Ageing by due date', 'Ageing method = Days since due date (adds a Not due column)'], ['As at an earlier date', 'N/A — MYOB\'s API gives today\'s open balances']],
    checks: ['Each customer\'s total due = Σ its age buckets, and the report total = Σ the invoices', '**Independent tie:** total due = the receivables account (type Accounts Receivable) on the Balance Sheet', 'Every unpaid invoice has a customer (and a due date when ageing by due date)'],
    golden: 'mySMB.com as at 9 Sep 2026 (days since invoice date): Daniel Lee 45.00 | 0.00 | 1,375.00 | 0.00 | 1,420.00 · Michael Thompson 534.75 · Sarah Mitchell 185.00 · Total 2,326.96 = the receivables account',
    fileName: 'myob-unpaid-invoices.html', tags: ['myob', 'unpaid-invoices', 'M32', 'receivables'],
  },
  {
    m: 'M32', skill: 'aged-receivables', name: 'MYOB Aged Receivables', report: 'ag', wave: 'Wave 1 (P1 — the unpaid invoices report aged by due date)',
    title: 'Aged receivables', menu: 'Reporting → Reports → Sales → Unpaid invoices (ageing by due date)',
    trigger: 'the user asks for aged receivables, aged debtors, an ageing of what customers owe, or overdue invoices by age',
    discovery: 'Call `list_invoices` once with `status` = `Open`, and `list_company_files` once. A `{"__error": …}` result is a failed call: report its message',
    dates: 'Always as at today — MYOB\'s API gives today\'s open balances. Ageing is by due date (`method` = `Due date`; set `Invoice date` for MYOB\'s default). The view is display `v` (`customers` | `invoices`).',
    members: [['Aged receivables', 'Customer | Not due | 1 - 30 | 31 - 60 | 61 - 90 | 90+ | Total due'], ['Invoices', 'Report = Invoices'], ['Ageing by invoice date', 'Ageing method = Days since invoice date']],
    checks: ['Each customer\'s total due = Σ its age buckets', '**Independent tie:** total due = the receivables account on the Balance Sheet', 'Every unpaid invoice has a customer and a due date'],
    golden: 'mySMB.com as at 9 Sep 2026: total 2,326.96 = the receivables account; overdue by due date as on the MYOB dashboard',
    fileName: 'myob-aged-receivables.html', tags: ['myob', 'aged-receivables', 'receivables', 'ageing'],
  },
  {
    m: 'M33, M34', skill: 'receivables-reconciliation', name: 'MYOB Receivables Reconciliation', report: 'rr', wave: 'Wave 1 (P1, delivery order 5; M34 P2)',
    title: 'Receivables reconciliation with tax', menu: 'Reporting → Reports → Sales → Receivables reconciliation with tax / Receivables reconciliation exceptions',
    trigger: 'the user asks for a receivables reconciliation, to reconcile debtors or accounts receivable, whether the customer balances match the receivables account, or receivables exceptions',
    discovery: 'Call `list_invoices` once with `status` = `Open`, and `get_balance_sheet` once with `date` = today, and `list_company_files` once. A `{"__error": …}` result is a failed call: report its message',
    dates: 'Always as at today (MYOB\'s API gives today\'s open balances; the kit sets `as_at`). Reconciliation with tax (M33) or exceptions (M34) is display `v` (`recon` | `exceptions`).',
    members: [['Receivables reconciliation with tax (M33)', 'Name | Amount outstanding | Tax outstanding per customer; Total; Receivables account; Out of balance amount'], ['Receivables reconciliation exceptions (M34)', 'Report = Reconciliation exceptions (the tie-out and its possible causes)'], ['As at an earlier date', 'N/A — MYOB\'s API gives today\'s open balances']],
    checks: ['**Independent tie:** total outstanding − the receivables account (Balance Sheet) = out of balance amount, 0.00 expected', 'Tax outstanding = each invoice\'s tax pro rata to what is still owed', 'Each invoice: subtotal + tax = total'],
    golden: 'mySMB.com as at 9 Sep 2026: Daniel Lee 1,420.00 / 129.09 · Michael Thompson 534.75 / 48.61 · Total 2,326.96 / 211.53 · Receivables account 2,326.96 · Out of balance 0.00',
    fileName: 'myob-receivables-reconciliation.html', tags: ['myob', 'receivables', 'reconciliation', 'M33', 'M34'],
  },
  {
    m: 'M38', skill: 'sales-register', name: 'MYOB Sales Register', report: 'sr', wave: 'Wave 1 (P1, delivery order 10)',
    title: 'Sales register', menu: 'Reporting → Reports → Sales → Sales register',
    trigger: 'the user asks for a sales register, a list of sales invoices for a period, or invoices by status',
    discovery: 'Call `list_invoices` once with `status` = `All`, `from_date` / `to_date` = the period, and `list_company_files` once. A `{"__error": …}` result is a failed call: report its message',
    dates: '`from_date` / `to_date` = the period (default: the financial year to date; display preset `p` = `this_fy_td`, `this_month`, `last_month`, `this_quarter`, `last_quarter`, `last_fy` or `custom`). `status` = `All`, `Open` or `Closed`. `as_at` is set by the kit. The view is display `v` (`register` | `customers`).',
    members: [['Sales register', 'Date | Invoice No. | Customer PO No. | Customer name | Total amount | Amount due | Status, totals row'], ['Customer sales', 'Report = Customer sales (M35)'], ['Quotes and orders', 'N/A — the connector reads invoices only']],
    checks: ['**Independent tie:** Σ sale amount (ex tax) = Income on the Profit and Loss for the period', 'Σ amount due = the receivables account on the Balance Sheet (when every open invoice is in the period; information otherwise)', 'Counts by status add up to the invoices listed'],
    golden: 'mySMB.com 1 Jul – 9 Sep 2026: 12 invoices, all Open (INV00000011 01/07/2026 Daniel Lee 1,375.00 · INV00000012 20/07/2026 Michael Thompson 528.00 …) · Total 2,326.96 / 2,326.96',
    fileName: 'myob-sales-register.html', tags: ['myob', 'sales-register', 'M38', 'sales'],
  },
  {
    m: 'M35', skill: 'customer-sales', name: 'MYOB Customer Sales', report: 'cs', wave: 'Wave 1 (P1, delivery order 11)',
    title: 'Customer sales', menu: 'Reporting → Reports → Sales → Customer sales',
    trigger: 'the user asks for customer sales, sales by customer, top customers, or how much each customer bought in a period',
    discovery: 'Call `list_invoices` once with `status` = `All`, `from_date` / `to_date` = the period, and `list_company_files` once. A `{"__error": …}` result is a failed call: report its message',
    dates: '`from_date` / `to_date` = the period (default: the financial year to date; display preset `p` as for the Sales register). `status` = `All`, `Open` or `Closed`. The view is display `v` (`customers` | `register`).',
    members: [['Customer sales', 'Customer name | Customer number | Sale amount | Tax | Current balance, totals row, top-10 chart and the largest customer\'s share'], ['Sales register', 'Report = Sales register (M38)'], ['Customer sales (detail, M36)', 'Not yet — invoice lines are not confirmed in the connector\'s invoice list']],
    checks: ['**Independent tie:** Σ sale amount (ex tax) = Income on the Profit and Loss for the period', 'Every customer\'s current balance adds up to the receivables account on the Balance Sheet', 'Counts by status add up to the invoices listed'],
    golden: 'mySMB.com 1 Jul – 9 Sep 2026: Daniel Lee 1,290.91 / 129.09 / 1,420.00 · Michael Thompson 486.14 / 48.61 / 534.75 · Σ sale amount 2,115.43 = P&L income',
    fileName: 'myob-customer-sales.html', tags: ['myob', 'customer-sales', 'M35', 'sales'],
  },
  {
    m: 'M05', skill: 'cash-movement', name: 'MYOB Cash Movement', report: 'cm', wave: 'Wave 1 (P1, delivery order 3)',
    title: 'Cash movement', menu: 'Reporting → Reports → Business → Cash movement',
    trigger: 'the user asks for cash movement, where the cash went, cash in and out, or how the bank balance changed over a period',
    discovery: 'Call `get_profit_and_loss_3m` once for the period (`reporting_basis` = `Accrual`), `get_balance_sheet` once at the period end, and `list_company_files` once. A `{"__error": …}` result is a failed call: report its message',
    dates: '`from_date` / `to_date` = the period (default: the financial year to date; display preset `p` as for the Profit and Loss). `prev_day` is derived by the kit — leave it. The view is display `v` (`cm` | `bank`).',
    members: [['Cash movement', 'The P&L for the period, then the change in every non-bank account as its effect on cash, Net Cash Movement in (Out), opening and closing bank balances'], ['Bank accounts', 'Report = Bank accounts (opening, movement, closing per bank account)'], ['Comparison with last year, monthly breakdown', 'Not yet']],
    checks: ['**Independent tie:** closing bank balance = opening bank balance + net cash movement (bank accounts on two Balance Sheets vs the P&L and every other account\'s change)', 'Net cash movement = net profit + the change in every non-bank account', 'Every account is classified, with at least one bank account', 'A year-end close inside the period is shown for information'],
    golden: 'mySMB.com 1 Jul – 9 Sep 2026: Net profit 1,610.48; receivables up 2,326.96 (uses cash); GST up 161.03; bank closing (555.45) = opening 0.00 + net cash movement (555.45)',
    fileName: 'myob-cash-movement.html', tags: ['myob', 'cash-movement', 'M05', 'cash'],
  },
  {
    m: 'M08', skill: 'general-ledger', name: 'MYOB General Ledger', report: 'gl', wave: 'Wave 1 (P1, delivery order 13)',
    title: 'General ledger', menu: 'Reporting → Reports → Business → General ledger',
    trigger: 'the user asks for a general ledger, GL, the transactions on a category or account, or every journal for a period',
    discovery: 'Call `list_journal_transactions` once with `from_date` / `to_date` = the period, and `list_company_files` once. Expect `{Count, Items:[{DisplayID, JournalType, DateOccurred, Description, Lines:[{Account{UID, Name, DisplayID}, Amount, IsCredit}]}]}`. A `{"__error": …}` result is a failed call: report its message',
    dates: '`from_date` / `to_date` = the period (default: this month; display preset `p` = `this_month`, `last_month`, `this_quarter`, `this_fy_td` or `custom`). `prev_day` and `fy_start` are derived by the kit — leave them. The view is display `v` (`accounts` | `transactions`).',
    members: [['General ledger', 'Code | Category name | Open | Debit | Credit | Net activity | Balance, one row per category with activity'], ['Transactions', 'Report = Transactions (every journal line)'], ['Tax amount per line', 'N/A — not in the journal list']],
    checks: ['Σ debits = Σ credits, and every journal transaction balances', '**Independent tie:** balance-sheet categories — open (Balance Sheet the day before) + net activity = the closing Balance Sheet', '**Independent tie:** income and expense categories — net activity = the Profit and Loss for the period'],
    golden: 'mySMB.com September 2026: 1-1110 Business Bank Account #1 open (555.45) → balance (555.45); 1-1200 Accounts Receivable 2,326.96 → 2,326.96 (no September activity)',
    fileName: 'myob-general-ledger.html', tags: ['myob', 'general-ledger', 'M08', 'journals'],
  },
];
