// MYOB Reports Prompt Library v1.2 families built on the tested kit. Each writes skills/<skill>.md (existing file stems, so the
// agent blueprint's skill ids do not change). Reports not listed here keep their prose skills.
module.exports = [
  {
    m: 'M04', skill: 'profit-and-loss', name: 'MYOB Profit and Loss', report: 'pnl', wave: 'Wave 1 (P1, delivery order 1)',
    title: 'Profit and loss', menu: 'Reporting → Reports → Business → Profit and loss',
    trigger: 'the user asks for a profit and loss, P&L, income statement, trading statement, net profit, income and expenses for a period, or a P&L comparison with last year',
    discovery: 'Call `get_profit_and_loss_3m` once with `from_date` = the financial-year start, `to_date` = today and `reporting_basis` = `Accrual`, and call `list_company_files` once. Expect `{StartDate, EndDate, ReportingBasis, AccountsBreakdown:[{Account:{UID,Name,DisplayID}, AccountTotal}]}` — one total per account and **no section totals** (the kit classifies each account with `list_accounts` and adds them up). An empty `AccountsBreakdown` means no activity, not an error. `{"__error": …}` is a failed call',
    dates: '`from_date` = start of the period asked for (default: financial-year start, e.g. `2026-07-01`); `to_date` = end of the period (default `"today"`). Set the display preset `p` to match (`this_fy_td` by default; `this_month`, `last_month`, `this_quarter`, `last_quarter`, `last_fy` or `custom`). Comparison dates are set by the kit from the Compare to control; leave their defaults.',
    members: [['Profit and loss', 'Report = Profit and Loss (default)'], ['Profit and loss as % of income', 'Report = P&L as % of income'], ['Profit and loss comparison', 'Compare to = Previous period / Previous year / Year to date (adds comparison, $ change and % change columns)'], ['Cash basis', 'Accounting method = Cash'], ['Breakdown by month / category / job', 'N/A — the MYOB API P&L summary returns one total per account (say so; offer the total view)']],
    checks: ['Every account on the P&L is classified (Income, Cost of Sales, Expense, Other Income, Other Expense from the chart of accounts)', 'Section totals = Σ their accounts', 'Gross Profit = Income − Cost of Sales; Net Profit = Gross Profit − Expenses + Other Income − Other Expenses', '**Independent tie:** for a financial-year-to-date range, Net Profit = Current Year Earnings on the Balance Sheet at the end date (a separate MYOB report); other ranges show this as information', 'Comparison period loaded (when Compare to is on)'],
    golden: 'mySMB.com, 1 Jul – 9 Sep 2026 accrual: Sales / Total income / Gross profit 2,115.43; Electricity & Gas 290.91; Office Supplies 132.27; Telephone & Internet 81.77; Total expenses 504.95; Net profit 1,610.48; last year 0.00. Live on 28 Sep 2026 (FY to date): Income 4,317.25, Expenses 2,134.49, Net profit 2,182.76',
    fileName: 'myob-profit-and-loss.html', tags: ['myob', 'profit-and-loss', 'M04', 'financial-statement'],
  },
  {
    m: 'M02', skill: 'balance-sheet', name: 'MYOB Balance Sheet', report: 'bs', wave: 'Wave 1 (P1, delivery order 2)',
    title: 'Balance sheet', menu: 'Reporting → Reports → Business → Balance sheet',
    trigger: 'the user asks for a balance sheet, statement of financial position, net assets, assets and liabilities as at a date, or a balance sheet comparison',
    discovery: 'Call `get_balance_sheet` once with `date` = today and `reporting_basis` = `Accrual`, and call `list_company_files` once. Expect `{AsOfDate, AccountsBreakdown:[{Account:{UID,Name,DisplayID}, AccountTotal}]}` — no totals; values are positive in each account\'s normal balance (an overdrawn bank is negative). The Equity section includes MYOB\'s Current Year Earnings account (this year\'s profit to date). `{"__error": …}` is a failed call',
    dates: '`as_at` = the balance date asked for (default `"today"`); set the display preset `a` to `today`, `end_last_month`, `end_last_quarter`, `end_last_fy` or `custom` to match. `fy_start` is derived by the kit from `as_at` — leave its default. `compare_as_at` is set by the Compare to control.',
    members: [['Balance sheet', 'Report = Balance Sheet (default)'], ['Balance sheet summary', 'Report = Summary (totals only)'], ['Comparison with last year / last month end', 'Compare to = Previous year / Previous month end'], ['Category levels 1–4, Consolidate', 'N/A — the MYOB API returns account totals only (header groupings are not reported); one company file per report']],
    checks: ["Total Assets = Total Liabilities + Total Equity. If they differ by exactly last financial year's net profit (a file not yet rolled over — MYOB's account summary then omits it), the report adds a computed equity line \"Prior year earnings not yet closed to Retained Earnings\" and an information line to roll over the year; any other difference fails and shows last year's profit for diagnosis", 'Every account on the Balance Sheet is classified', 'Section totals = Σ their accounts', '**Independent tie:** Current Year Earnings = P&L Net Profit from the financial-year start to the as-at date (a separate MYOB report)', 'Comparison date loaded (when Compare to is on)'],
    golden: 'mySMB.com as at 9 Sep 2026: Bank (555.45); Accounts receivable 2,326.96; Total assets 1,771.51; GST 161.03; Total liabilities 161.03; Net assets / Current year earnings / Total equity 1,610.48. Live on 28 Sep 2026: Total assets 3,896.01 (receivables 4,328.96, bank (432.95)), Total liabilities 1,713.25, Total equity 2,182.76',
    fileName: 'myob-balance-sheet.html', tags: ['myob', 'balance-sheet', 'M02', 'financial-statement'],
  },
];
