// Card metadata for the reports catalogue (Q02): category + plain-English description per family.
// Built status comes from families.js; wave and Q-ID from the library index.
module.exports = {
  categories: ['Financial statements', 'Receivables and payables', 'Taxes', 'Sales and expenses', 'Dashboards', 'Planning', 'Accountant', 'Projects and inventory', 'Payroll', 'Packs and tools'],
  cards: {
    Q17: ['Financial statements', 'Profit and Loss', 'Income, cost of sales, gross profit, expenses and net earnings for any period, with comparisons, monthly columns and % of income.'],
    Q18: ['Financial statements', 'Balance Sheet', 'Assets, liabilities and equity as of any date, with comparison dates and a check that net earnings tie to the P&L.'],
    Q19: ['Financial statements', 'Statement of Cash Flows', 'Operating, investing and financing cash flows, opening to closing cash, with a waterfall chart.'],
    Q22: ['Financial statements', 'Trial Balance', 'Debit and credit balance for every account as of any date, checked to balance.'],
    Q24: ['Receivables and payables', 'Accounts Receivable Ageing', 'Who owes you, by ageing band — summary, detail, collections, open invoices and customer balances.'],
    Q26: ['Receivables and payables', 'Accounts Payable Ageing', 'Who you owe, by ageing band — summary, detail, unpaid bills and supplier balances, with a payment schedule.'],
    Q28: ['Taxes', 'GST Summary (BAS)', 'BAS labels G1, 1A, 1B and 9 for any period, with the refund or payment due.'],
    Q15: ['Taxes', 'GST overview', 'GST collected, paid and the net refund or payable this period against the last, with the GST liability.'],
    Q34: ['Taxes', 'ATO reports', 'Payment summaries and tax file declaration reporting from the payroll app.'],
    Q25: ['Sales and expenses', 'Sales and customers', 'Sales by customer and by product or service, income by customer, customer and product lists, and quotes.'],
    Q27: ['Sales and expenses', 'Expenses and suppliers', 'Expenses by supplier with concentration, the purchase list, cheque detail and supplier contacts.'],
    Q36: ['Sales and expenses', 'Exchange gains and losses', 'Realised gains and losses from the P&L, and an estimate of unrealised gains on open foreign-currency bills and invoices.'],
    Q00: ['Dashboards', 'Business at a glance', 'The QuickBooks homepage: profit and loss, spending, bank balances and 12-month cash flow.'],
    Q20: ['Dashboards', 'Business Snapshot', 'My income and my expenses by account, the previous year, who owes me and who I owe.'],
    Q07: ['Dashboards', 'Cash flow overview', "Today's cash position, the 12-month cash balance, money in and money out this month, and a 30-day projection."],
    Q06: ['Dashboards', 'Performance centre', 'KPI charts over time — revenue, expenses, profit, cash flow, ageing, current and quick ratios.'],
    Q01: ['Dashboards', 'Business feed', "A 'report ready' profit and loss card for last month with insights on profit, spending, money owed and bills."],
    Q10: ['Dashboards', 'Expenses & Pay Bills overview', 'Unpaid and paid bills, spend over time, spend by supplier and days payable outstanding.'],
    Q11: ['Dashboards', 'Sales & Get Paid overview', 'Income over time, unpaid and overdue invoices, payments received and days sales outstanding.'],
    Q12: ['Dashboards', 'Customer Hub overview', 'Open quotes, projects in progress, unpaid and overdue invoices, and what needs attention.'],
    Q08: ['Planning', 'Budgets', 'Budget vs actuals, the budget overview and profit and loss budget performance for your QuickBooks budgets.'],
    Q09: ['Planning', 'Forecasts', 'A projection of future results from past trends — clearly labelled as an estimate.'],
    Q16: ['Accountant', 'Client overview', 'Books health check: bank balances, undeposited funds, uncategorised items, old ageing, negative accounts and transaction volume.'],
    Q23: ['Accountant', 'General Ledger', 'Every transaction by account with beginning and running balances, plus the journal, transaction list and account list.'],
    Q21: ['Accountant', 'Audit Log', 'Who changed what and when — built from the Audit Log export you attach.'],
    Q13: ['Projects and inventory', 'Projects overview', 'Income, profit and margin for each project, and estimates vs actual income.'],
    Q29: ['Projects and inventory', 'Project profitability', 'Income, costs, profit and margin by project, and estimates vs actuals.'],
    Q14: ['Projects and inventory', 'Inventory overview', 'Products low on stock or out of stock, with quantities on order.'],
    Q30: ['Projects and inventory', 'Inventory valuation', 'Stock on hand and its value, inventory status, open purchase orders and a stocktake worksheet.'],
    Q31: ['Payroll', 'Employees and time', 'Employee contacts, time activities and timesheets.'],
    Q32: ['Payroll', 'Payroll reports', 'Gross to net, PAYG withholding, super, pay categories and pay run audits from the payroll app.'],
    Q33: ['Payroll', 'Employee reports', 'Employee details, payment history, leave balances and leave liability.'],
    Q04: ['Packs and tools', 'Management report packs', 'Print-ready packs — cover, contents, executive summary, statements and notes — for the board or month end.'],
    Q35: ['Packs and tools', 'Custom report builder', 'Any QuickBooks standard report — sales by class or location, balance detail, transaction lists — in QuickBooks styling.'],
    Q37: ['Packs and tools', 'Ask a question', 'Ask in plain English and get the figure, the period and where it came from, then the full report if you want it.'],
    Q02: ['Packs and tools', 'Reports catalogue', 'This page — every QuickBooks report and whether it is live yet.'],
    Q03: ['Packs and tools', 'Custom reports', 'Saved report settings — use your saved reports in the Reports library.'],
    Q05: ['Packs and tools', 'Spreadsheet Sync', 'Reports in Excel — every report here has Download Excel.'],
    Q38: ['Packs and tools', 'Open in QuickBooks', 'Every report can open the matching QuickBooks report, and its Excel export lists the report settings.'],
    Q39: ['Packs and tools', 'Download and share', 'Every report downloads to PDF and Excel and can be shared from the report window.']
  }
};
