// Per-family skill metadata. Source of truth for the skill prose; code blocks come from reports/<id>.manifest.json and reports/<id>.cfg.js.
const W2 = require("./families-w2.js"), W3 = require("./families-w3.js"), W4 = require("./families-w4.js");
module.exports = [
  { id: 'pnl', q: 'Q17', skill: 'quickbooks-profit-and-loss', title: 'Profit and Loss family', menu: 'Reports › Standard reports › Business overview › Profit and Loss',
    trigger: 'the user asks for a profit and loss, P&L, income statement, profit report, P&L by month / quarter / customer / class / location, P&L comparison, P&L as % of income or year-to-date comparison',
    discovery: "`get_report_profit_and_loss` with `start_date`, `end_date`, `accounting_method` — expect `Rows.Row[]` sections with `group` Income, COGS, GrossProfit, Expenses, NetOperatingIncome, OtherIncome, OtherExpenses, NetIncome",
    dates: 'Preset `this_fy_td`: `start_date` = first day of the financial year (CompanyInfo `FiscalYearStartMonth`), `end_date` = `"today"` (config: today\'s date). `compare_start` / `compare_end` = the same two dates one year earlier. For a user-named period, set `p` in `display` to the matching preset key (or `custom`) and the dates to that period.',
    fileName: 'quickbooks-profit-and-loss.html', tags: ['quickbooks', 'profit-and-loss', 'finance'],
    members: [['Profit and Loss', 'Display columns by = Total only'], ['P&L by Month / Quarterly P&L Summary', 'Display columns by = Months / Quarters'], ['P&L by Customer', 'Display columns by = Customers (also Suppliers, Classes, Locations, Products/Services)'], ['P&L Comparison', 'Compare to = Previous period / Previous year'], ['P&L year-to-date comparison', 'Compare to = Year-to-date'], ['P&L as % of total income', 'Report = P&L as % of total income'], ['P&L Detail', 'Not in this skill — transaction detail (ProfitAndLossDetail) is a Wave 2 member'], ['P&L by Tag Group', 'N/A — tags are not exposed by the Accounting API']],
    checks: ['Total for Income = Σ income accounts', 'Gross Profit = Income − Cost of Sales', 'Net Earnings = Gross Profit + Other Income − Expenses − Other Expenses', 'QuickBooks returned the requested period (Header StartPeriod / EndPeriod)', 'Comparison deltas recomputed from the comparison period (when Compare to is on)'],
    golden: 'August 2026 (accrual): SaaS – Consulting Services A$7,000.00 · SaaS – Subscription Licence A$57,833.33 · Total for Income A$64,833.33 · Gross Profit A$78,608.34 · Total for Expenses A$261,712.88 · Net Earnings −A$175,286.75. Note: Gross Profit above Income means Cost of Sales is a net credit (−A$13,775.01) — the report flags this in Sources & limitations.' },
  { id: 'bs', q: 'Q18', skill: 'quickbooks-balance-sheet', title: 'Balance Sheet family', menu: 'Reports › Standard reports › Business overview › Balance Sheet',
    trigger: 'the user asks for a balance sheet, statement of financial position, net assets, balance sheet comparison, balance sheet summary, working capital or current ratio at a date',
    discovery: "`get_report_balance_sheet` with `end_date`, `accounting_method` — expect sections with `group` TotalAssets, CurrentAssets, BankAccounts, AR, OtherCurrentAssets, TotalLiabilitiesAndEquity, Liabilities, CurrentLiabilities, AP, CreditCards, Equity, and an Equity row labelled Net Income",
    dates: 'As-of preset `today` (`a` in `display`): `as_at` = `"today"` (config: today\'s date); `fy_start` = first day of the financial year containing `as_at` (the report re-derives it on every change); `compare_as_at` = the same date one year earlier.',
    fileName: 'quickbooks-balance-sheet.html', tags: ['quickbooks', 'balance-sheet', 'finance'],
    members: [['Balance Sheet', 'Default view'], ['Balance Sheet Comparison', 'Compare to = Previous month end / Previous year'], ['Balance Sheet Summary', 'Report = Balance Sheet Summary (account lines collapsed)'], ['Balance Sheet by Month / Quarter / Class / Location', 'Display columns by'], ['Balance Sheet Detail', 'N/A here — transaction level, use the General Ledger family (Wave 2)'], ['Statement of Changes in Equity', 'N/A — not exposed by the Accounting API']],
    checks: ['Total for Assets = Total for Liabilities + Equity', "Each 'Total for' = Σ its rows", 'Net Earnings = P&L financial year to date (tie to get_report_profit_and_loss from the FY start to the as-of date)', 'QuickBooks returned the requested date', 'Comparison deltas recomputed (when Compare to is on)'],
    golden: 'As of 31 Aug 2026: Wise-AUD A$147,337.00 · ANZ A$99.00 · PHP A$2.69 · A/R A$91,905.00 · Prepaid expenses A$11,966.18 · Security Deposit A$28,800.00 · Intangibles – Trademarks A$18,294.11 · A/P A$175,222.57 · A/P – USD A$95,858.82 · Doug\'s Amex Card A$25,803.79 · Total for Liabilities and Shareholders\' Equity A$298,398.60.' },
  { id: 'scf', q: 'Q19', skill: 'quickbooks-statement-of-cash-flows', title: 'Statement of Cash Flows', menu: 'Reports › Standard reports › Business overview › Statement of Cash Flows',
    trigger: 'the user asks for a statement of cash flows, cash flow statement, where the cash went, operating / investing / financing cash flow, or a cash waterfall',
    discovery: "`get_report_cash_flow` with `start_date`, `end_date` — expect `group` OperatingActivities (with a Net Income row and an OperatingAdjustments section), InvestingActivities, FinancingActivities, CashIncrease, BeginningCash, EndingCash. AU / IFRS companies may return NO BeginningCash or EndingCash rows at all — only CashIncrease (\"Net increase (decrease) in cash and cash equivalents\"); the report then takes closing cash from the bank accounts on a balance sheet at the end date (`QB.bankCash`) and works opening cash back",
    dates: 'Preset `this_fy_td`: `start_date` = FY start, `end_date` = `"today"`; compare dates = one year earlier.',
    fileName: 'quickbooks-statement-of-cash-flows.html', tags: ['quickbooks', 'cash-flow', 'finance'],
    members: [['Statement of Cash Flows', 'Default; Display columns by Months / Quarters / Years; Compare to'], ['Accounting method', 'Not offered — QuickBooks presents this report on its own method; the footer shows the basis QuickBooks returned']],
    checks: ['Cash at end = Cash at beginning + Net cash increase', 'Net cash increase = Operating + Investing + Financing', 'Operating = Net Earnings + Σ adjustments', "Each 'Total for' = Σ its rows", 'QuickBooks returned the requested period'],
    golden: 'August 2026: Net Earnings −A$175,286.75 with working-capital adjustments (Accounts Receivable, Prepaid expenses, Security Deposit, Accounts Payable, Doug\'s Amex Card, GST Liabilities Payable).' },
  { id: 'ar', q: 'Q24', skill: 'quickbooks-aged-receivables', title: 'Accounts receivable family', menu: 'Reports › Standard reports › Who owes you',
    trigger: 'the user asks for aged receivables, A/R ageing (aging), who owes us, debtors, overdue invoices, collections report, open invoices or customer balances',
    discovery: "`get_report_aged_receivables` (no params) — expect columns Customer | Current | 1 - 30 | 31 - 60 | 61 - 90 | 91 and over | Total, one Data row per customer and a GrandTotal summary; note the ageing date in Header (Option report_date or EndPeriod)",
    dates: 'No date inputs: QuickBooks ages as of today. The header shows the date QuickBooks returned.',
    fileName: 'quickbooks-aged-receivables.html', tags: ['quickbooks', 'receivables', 'ageing', 'finance'],
    members: [['A/R ageing summary', 'Report = A/R ageing summary'], ['A/R ageing detail', 'Report = A/R ageing detail (get_report_aged_receivable_detail)'], ['Collections Report', 'Report = Collections report (overdue open invoices, oldest first)'], ['Open Invoices', 'Report = Open invoices'], ['Customer Balance Summary', 'Report = Customer balance summary'], ['Customer Balance Detail, Invoice List, Invoices and Received Payments, Statement List, Terms List, Unbilled charges, Unbilled time', 'Wave 2 members'], ['As-of date, ageing method, days per period, number of periods, min. days past due', 'N/A — the connector does not pass report_date / aging_period / num_periods / aging_method / past_due yet (connector change requested)']],
    checks: ['Row total = Σ bands for every customer', 'Grand total = Σ customers (each band and total)', 'Grand total = A/R on the balance sheet (today)', 'Ageing detail open balance = summary total'],
    golden: 'A/R as of 10 Sep 2026: Civica Pty Ltd A$39,105.00 (current); Total A$39,105.00.' },
  { id: 'ap', q: 'Q26', skill: 'quickbooks-aged-payables', title: 'Accounts payable family', menu: 'Reports › Standard reports › What you owe',
    trigger: 'the user asks for aged payables, A/P ageing (aging), who we owe, creditors, unpaid bills, bills due, a payment schedule or supplier balances',
    discovery: "`get_report_aged_payables` (no params) — expect columns Supplier | Current | 1 - 30 | 31 - 60 | 61 - 90 | 91 and over | Total, one Data row per supplier and a GrandTotal summary",
    dates: 'No date inputs: QuickBooks ages as of today.',
    fileName: 'quickbooks-aged-payables.html', tags: ['quickbooks', 'payables', 'ageing', 'finance'],
    members: [['A/P ageing summary', 'Report = A/P ageing summary'], ['A/P ageing detail', 'Report = A/P ageing detail'], ['Unpaid Bills', 'Report = Unpaid bills'], ['Supplier Balance Summary', 'Report = Supplier balance summary'], ['Bills and Applied Payments, Bill Payment List, Supplier Balance Detail', 'Wave 2 members'], ['As-of date and ageing options', 'N/A — connector change requested (as for A/R)']],
    checks: ['Row total = Σ bands for every supplier', 'Grand total = Σ suppliers (each band and total)', 'Grand total = A/P on the balance sheet (today)', 'Ageing detail open balance = summary total'],
    golden: 'A/P as of 10 Sep 2026: Total A$265,179.79 — current A$68,299.44 · 1-30 A$17,233.37 · 31-60 A$63,062.81 · 61-90 A$48,324.50 · 91+ A$68,259.67.' },
  { id: 'tb', q: 'Q22', skill: 'quickbooks-trial-balance', title: 'Trial Balance family', menu: 'Reports › Standard reports › For my accountant › Trial Balance',
    trigger: 'the user asks for a trial balance, TB, debits and credits by account, or to check the books balance',
    discovery: "`get_report_trial_balance` with `end_date`, `accounting_method` — expect columns '' | Debit | Credit, Data rows per account and a GrandTotal TOTAL row",
    dates: 'As-of preset `today`: `as_at` = `"today"`; `fy_start` = FY start of `as_at`.',
    fileName: 'quickbooks-trial-balance.html', tags: ['quickbooks', 'trial-balance', 'finance'],
    members: [['Trial Balance', 'Default'], ['Adjusted Trial Balance', 'N/A — adjusting-entry columns are not exposed'], ['Custom Summary Report', 'Use Profit and Loss / Balance Sheet with Display columns by']],
    checks: ['Σ debits = Σ credits', 'TOTAL row = Σ account rows (debit and credit)', 'QuickBooks returned the requested date'],
    golden: 'As of 31 Aug 2026: TOTAL A$4,021,894.41 / A$4,021,894.41 (Wise-AUD A$147,337.00 · A/R A$91,905.00 · A/P A$175,222.57 …).', wave: 'Wave 2 story (Train 02) — delivered early because it was already validated on 18 Sep' },
  { id: 'gst', q: 'Q28', skill: 'quickbooks-gst-bas', title: 'GST and PAYG family (BAS)', menu: 'Reports › Standard reports › Manage Taxes › GST Summary',
    trigger: 'the user asks for GST, a GST summary, BAS, BAS labels (G1, 1A, 1B, 9), GST payable or refund, the activity statement, or PAYG withholding',
    discovery: "`get_report_tax_summary` with `start_date`, `end_date`, `accounting_method` — for an AU company expect rows labelled Net amount for G1 · Tax amount for G1 · GST-Free sales · G1 TOTAL SALES · 1A GST ON SALES · 1B GST ON PURCHASES · 8A · 8B · 9 REFUND OR PAYMENT DUE. QuickBooks returns BAS figures only when `agency_id` names the tax agency: call `list_tax_agency` too and set the `agency_id` default to the Australian Tax Office's `Id` (the report also finds the ATO itself on open). With the agency, NoReportData means no GST transactions in the period — a nil period, shown as A$0, but only when a history-wide Tax Summary for the agency (gst_probe) has data; if the agency has no GST at any time, say GST is unavailable (the connector may not be passing agency_id)",
    dates: 'Preset `this_quarter` (current BAS quarter) or `last_quarter` when the user is preparing the BAS just lodged; dates = that quarter.',
    fileName: 'quickbooks-gst-summary.html', tags: ['quickbooks', 'gst', 'bas', 'tax'],
    members: [['GST Summary', 'Report = GST Summary'], ['PAYG Withholding Summary / Details / Amendment', 'Report = PAYG Withholding Summary shows an explicit N/A — payroll lives in Employment Hero'], ['GST Details, GST Liability, GST Amendment, TPAR, Transactions without GST, Transaction Detail by Tax Code', 'Wave 2 members']],
    checks: ['1A − 1B = 9', 'G1 = net amount + tax amount + GST-free sales', 'GST Liabilities on the balance sheet at period end (information)', 'QuickBooks returned the requested period'],
    golden: 'Jul–Sep 2026: G1 A$140,305.00 · 1A A$12,755.00 · 1B A$19,687.77 · 9 Refund or payment due A$−6,932.77.' },
  { id: 'gst-overview', q: 'Q15', skill: 'quickbooks-gst-overview', title: 'GST overview (BAS centre)', menu: 'All apps › GST › Overview',
    trigger: 'the user asks for the GST overview, GST position, BAS centre, how much GST we owe or get back this quarter, or GST collected vs paid',
    discovery: "`list_tax_agency` (set the `agency_id` default to the Australian Tax Office's `Id`), then `get_report_tax_summary` with that `agency_id` for the current and previous period (same shape as the GST Summary)",
    dates: 'Preset `this_quarter`; compare = previous quarter (`c` = `prev_period`).',
    fileName: 'quickbooks-gst-overview.html', tags: ['quickbooks', 'gst', 'bas', 'dashboard'],
    members: [['GST overview tiles (refund/payable, collected, paid)', 'Built'], ['History', 'This and the previous period'], ['To do / Payments tabs, Export workpapers, Prepare BAS or IAS', 'N/A — BAS centre actions are not in the Accounting API']],
    checks: ['Refund / payable = GST collected − GST paid', 'Ties to GST Summary 1A / 1B (same source)', 'Previous period loaded'],
    golden: 'Jul–Sep 2026: GST refund $6,932 (collected $12,755, paid $19,687).' },
  { id: 'business-snapshot', q: 'Q20', skill: 'quickbooks-business-snapshot', title: 'Business Snapshot', menu: 'Reports › Standard reports › Business overview › Business Snapshot',
    trigger: 'the user asks for the business snapshot, my income and my expenses, income and expense breakdown with last year, or who owes me and who I owe on one page',
    discovery: "`get_report_profit_and_loss` (by account) plus `get_report_aged_receivables` and `get_report_aged_payables`",
    dates: 'Preset `last_month`; compare = the same month last year (`c` = `prev_year`).',
    fileName: 'quickbooks-business-snapshot.html', tags: ['quickbooks', 'dashboard', 'snapshot'],
    members: [['My income / My expenses (donuts)', 'Built'], ['Previous year income / expense comparison', 'Built'], ['Who owes me / Who I owe', 'Built (A/R and A/P ageing)']],
    checks: ['My income donut total = P&L income (Income + Other Income)', 'My expenses donut total = P&L expenses (Cost of Sales + Expenses + Other Expenses)', 'Who owes me total = A/R ageing total', 'Who I owe total = A/P ageing total'],
    golden: 'Income A$72,532 · Expenses A$247,819 · A/R A$39,105.00 · A/P A$265,179.79.',
    note: 'This replaces the 18 Sep "quickbooks-business-snapshot" composite, which was really a Homepage / Performance-centre style dashboard. The true Q20 layout (donuts + Who owes me / Who I owe) is built here; the composite dashboards are Q00, Q06 and Q07.' },
  { id: 'homepage', q: 'Q00', skill: 'quickbooks-homepage', title: 'Homepage — Business at a glance', menu: 'Home › Business at a glance',
    trigger: 'the user asks for the QuickBooks homepage, business at a glance, a dashboard, how the business is going, net profit last month, spending last 30 days or bank balances',
    discovery: "`get_report_profit_and_loss` by Month, `list_account` (Bank, Credit Card), `get_report_cash_flow` by Month",
    dates: 'No manual dates: the page sets each widget\'s window on every open (P&L: selected period and the one before; Expenses: last 30 days; Cash flow: 12 months). Leave the manifest defaults as given, but replace each with a valid date near today.',
    fileName: 'quickbooks-business-at-a-glance.html', tags: ['quickbooks', 'dashboard', 'homepage'],
    members: [['Profit & Loss widget', 'Period menu on the card: Last month / This month / Last quarter / This quarter'], ['Expenses widget', 'Last 30 days by category'], ['Bank accounts widget', "'In QuickBooks' balances; bank-feed balance N/A"], ['Cash flow widget', '12-month cash balance and net money in/out']],
    checks: ['Net profit = Income − Expenses', 'Category shares sum to the spending total', "Bank 'In QuickBooks' = ledger cash (Cash at end of period today)"],
    golden: 'Net profit for August −A$175,287 · Income A$72,532 · Expenses A$247,819 · Spending last 30 days A$245,491 · Cash balance A$145,321.' },
  { id: 'cash-flow-overview', q: 'Q07', skill: 'quickbooks-cash-flow-overview', title: 'Cash flow overview', menu: 'Reports › Financial planning › Cash flow overview',
    trigger: 'the user asks for the cash flow overview, cash position today, money in and money out this month, overdue invoices and bills, or a cash projection',
    discovery: "`list_account` (Bank, Credit Card), `get_report_cash_flow` by Month, `list_invoice` / `list_bill` with Balance > '0'",
    dates: 'No manual dates: the chart window (12 months to today) is set on every open.',
    fileName: 'quickbooks-cash-flow-overview.html', tags: ['quickbooks', 'cash', 'dashboard'],
    members: [["Today's cash balance (all / bank / credit cards)", 'Built — All accounts = bank less credit card balances (stated on the tile)'], ['Cash balance chart / Money in/out', 'Report = Cash balance | Money in/out'], ['Monthly outlook — Money in / Money out, Upcoming | Paid', 'Built'], ['30-day projection', 'Cash + invoices due − bills due within 30 days'], ['Bank-feed balances, Link another account', 'N/A — bank feeds are not in the Accounting API']],
    checks: ['All accounts = bank accounts − credit card balances', 'Upcoming + paid = month totals (information)', 'Cash balance chart ends at the bank balance in QuickBooks', 'All data sources loaded'],
    golden: "Today's cash balance A$145,321 · overdue bills 30 (−A$182,705) · open invoices 1 (A$39,105)." },
  { id: 'performance-centre', q: 'Q06', skill: 'quickbooks-performance-centre', title: 'Performance centre (KPI charts)', menu: 'Reports › Performance centre',
    trigger: 'the user asks for the performance centre, KPI charts, revenue / expenses / gross profit / net profit over time, current ratio, quick ratio, or a KPI dashboard',
    discovery: "`get_report_profit_and_loss`, `get_report_balance_sheet` and `get_report_cash_flow`, each with `summarize_column_by` = Month; ageing reports",
    dates: 'Preset `this_fy_td`; compare dates one year earlier.',
    fileName: 'quickbooks-performance-centre.html', tags: ['quickbooks', 'kpi', 'dashboard'],
    members: [['Expenses / Revenue / Gross profit / Net profit over time', 'Built, with Compare to'], ['Cash flow', 'Net cash flow by month'], ['A/R and A/P by ageing periods', "Built on QuickBooks' 30-day bands"], ['Current ratio / Quick ratio by time', 'Built with a 1.00 target line'], ['Revenue / expense targets', 'N/A — needs a budget (Budgets family, Wave 2)'], ['Quick-add charts and custom chart builder', 'N/A in this version']],
    checks: ['Chart totals = underlying P&L totals (Σ months = Total column)', 'Net cash flow chart = Statement of Cash Flows total', 'Current ratio = current assets ÷ current liabilities (latest month)', 'A/R and A/P ageing bands sum to their totals'],
    golden: 'This year to date: Total expenses A$1,628,002.07 · Total revenue A$110,333.35 · Gross profit −A$18,498.38 · Net profit −A$1,637,546.28 · Net cash flow A$20,292.19 · A/R A$39,105.00 · A/P A$265,179.79 · Current ratio 1.00 · Quick ratio 1.00.' },
  { id: 'management-reports', q: 'Q04', skill: 'quickbooks-management-reports', title: 'Management reports (report packs)', menu: 'Reports › Management reports',
    trigger: 'the user asks for a management report, board pack, report pack, company financials pack, month-end pack, BAS workpapers or a PDF pack of the statements',
    discovery: "`get_report_profit_and_loss`, `get_report_balance_sheet`, `get_report_cash_flow`, ageing reports and `get_report_tax_summary`",
    dates: 'Custom period — the pack period the user asks for (default: financial year to the end of last month).',
    fileName: 'quickbooks-management-report.html', tags: ['quickbooks', 'management-report', 'pack'],
    members: [['Basic Company Financials', 'Cover, contents, executive summary, P&L, Balance Sheet, end notes'], ['Expanded Company Financials', 'Adds Statement of Cash Flows, A/R and A/P ageing'], ['BAS workpapers', 'Cover, contents, GST Summary, P&L, end notes'], ['SPFR Company', 'N/A — needs accountant-authored notes and policies']],
    checks: ['P&L identities', 'Balance Sheet: Total for Assets = Total for Liabilities + Equity', 'Cash Flows: Cash at end = beginning + net increase (Expanded)', 'A/R and A/P ageing TOTAL = Σ rows (Expanded)', 'GST Summary: 1A − 1B = 9 (BAS workpapers)', 'Table of contents page numbers match the page order'],
    golden: 'Cover: For the period ended 31 December 2026 (This year).' }
].concat(W2, W3, W4);
