// Wave 3 family metadata — appended to families.js.
module.exports = [
  { id: 'inventory-overview', q: 'Q14', skill: 'quickbooks-inventory-overview', title: 'Inventory overview', menu: 'All apps › Inventory › Overview', wave: 'Wave 3 (Train 05)',
    trigger: 'the user asks for the inventory overview, what is low on stock or out of stock, what to reorder, or stock levels against reorder points',
    discovery: "`list_item` with Type = 'Inventory' — expect `QueryResponse.Item[]` with Name, Sku, QtyOnHand, ReorderPoint; `get_report_inventory_valuation_summary`. Verify on first run: the sample company had no inventory",
    dates: 'No dates: QuickBooks values inventory as of today.',
    fileName: 'quickbooks-inventory-overview.html', tags: ['quickbooks', 'inventory', 'dashboard'],
    members: [['Low on stock', 'Quantity on hand at or below the reorder point, with quantity on order'], ['Out of stock', 'Quantity on hand zero or below'], ['Inventory Valuation reports', 'Switch Report to Inventory Valuation Summary, Inventory Status, Open Purchase Order List or Stocktake Worksheet'], ['Create actions (add product, sales order, purchase order, adjust inventory, shipping label)', 'N/A — use QuickBooks']],
    checks: ['Inventory Valuation quantity = Σ item quantity on hand', 'Σ asset value = Inventory Asset account', 'Inventory Valuation TOTAL = Σ products', 'Out-of-stock and low-stock counts equal the item query (information)'],
    golden: 'Captured empty (0 low on stock / 0 out of stock) — verify on a company with inventory.' },
  { id: 'inventory', q: 'Q30', skill: 'quickbooks-inventory', title: 'Inventory family', menu: 'Reports › Standard reports › Inventory', wave: 'Wave 3 (Train 05)',
    trigger: 'the user asks for inventory valuation, stock on hand value, inventory status, open purchase orders or a stocktake worksheet',
    discovery: "`get_report_inventory_valuation_summary` — expect columns '' | SKU | Qty | Asset Value | Calc. Avg with a GrandTotal TOTAL row; `list_item` (Inventory); `list_account` (AccountSubType Inventory); `list_purchase_order`. Verify on first run",
    dates: 'No dates: as of today.',
    fileName: 'quickbooks-inventory-valuation.html', tags: ['quickbooks', 'inventory'],
    members: [['Inventory Valuation Summary', 'Report = Inventory Valuation Summary'], ['Inventory Status', 'Report = Inventory Status (on hand, reorder point, on PO)'], ['Open Purchase Order List', 'Report = Open Purchase Order List'], ['Stocktake Worksheet', 'Report = Stocktake Worksheet (print with Download PDF)'], ['Inventory Valuation Detail, Open Purchase Order Detail', 'N/A — not Accounting API reports']],
    checks: ['Σ asset value = Inventory Asset account', 'Inventory Valuation quantity = Σ item quantity on hand', 'Inventory Valuation TOTAL = Σ products'],
    golden: 'Layout per QBO documentation: Product/Service | SKU | Qty | Asset value | Calc. avg cost.' },
  { id: 'customer-hub', q: 'Q12', skill: 'quickbooks-customer-hub', title: 'Customer Hub overview', menu: 'All apps › Customer Hub › Overview', wave: 'Wave 3 (Train 05)',
    trigger: 'the user asks for the customer hub, open quotes, projects in progress, unpaid or overdue invoices by customer, or what needs attention with customers',
    discovery: "`list_customer`, `list_estimate`, `list_invoice` (Balance > '0'), `get_report_aged_receivables`",
    dates: 'No manual dates: quotes and invoices from the last 365 days, recomputed on every open.',
    fileName: 'quickbooks-customer-hub.html', tags: ['quickbooks', 'customers', 'dashboard'],
    members: [['Customers funnel', 'Open quotes · in-progress projects · unpaid invoices (opportunities and reviews N/A)'], ['Overdue invoices', 'Overdue and all unpaid'], ['Open quotes', 'Pending quotes with expiry'], ['Needs attention', 'Overdue invoices and quotes expiring within 7 days (Customer Hub tasks are not in the API)']],
    checks: ['Unpaid invoices = A/R ageing total', 'Funnel counts equal the entity queries (information)'],
    golden: 'Funnel counts 0 · 0 · 0 · 1 · 0; overdue invoices A$0.00.' },
  { id: 'projects-overview', q: 'Q13', skill: 'quickbooks-projects-overview', title: 'Projects overview', menu: 'All apps › Projects › Overview', wave: 'Wave 3 (Train 05)',
    trigger: 'the user asks for the projects overview, how projects are going, project income and profit, or estimates vs actual income for projects',
    discovery: "`get_report_profit_and_loss` with `summarize_column_by` = Customers (one column per customer and project); `list_customer` — projects carry IsProject = true (older companies: Job = true). Verify on first run: the sample company had no projects",
    dates: 'Preset `this_fy_td`.',
    fileName: 'quickbooks-projects-overview.html', tags: ['quickbooks', 'projects', 'dashboard'],
    members: [['Estimates vs actual income', 'Report = Estimates vs actuals by project'], ['Project Profitability Summary', 'Report = Project Profitability Summary'], ['Projects overview', 'Income and profit per project, margin per project chart']],
    checks: ['Profit = income − costs (each project)', 'Σ customer and project columns = P&L total'],
    golden: 'Captured empty (Total Income A$0, no projects) — verify on a company with projects.' },
  { id: 'projects', q: 'Q29', skill: 'quickbooks-projects', title: 'Projects family', menu: 'Reports › Standard reports › Projects', wave: 'Wave 3 (Train 05)',
    trigger: 'the user asks for project profitability, the project profitability summary, profit or margin by project, or estimates vs actuals by project',
    discovery: 'Same as the Projects overview: P&L by Customers + `list_customer` + `list_estimate`',
    dates: 'Preset `this_fy_td`.',
    fileName: 'quickbooks-project-profitability.html', tags: ['quickbooks', 'projects'],
    members: [['Project Profitability Summary', 'Project | Income | Costs | Profit | Margin %'], ['Estimates vs. actuals by project', 'Report = Estimates vs actuals by project']],
    checks: ['Profit = income − costs (each project)', 'Σ customer and project columns = P&L total'],
    golden: 'Layout per QBO documentation: Project | Income | Costs | Profit | Margin %.' },
  { id: 'fx', q: 'Q36', skill: 'quickbooks-exchange-gains-losses', title: 'Exchange gains and losses (multi-currency)', menu: 'Reports › Standard reports › Business overview', wave: 'Wave 3 (Train 06)',
    trigger: 'the user asks for exchange gains or losses, FX gains, realised or unrealised currency gains, or foreign-currency exposure on open bills and invoices',
    discovery: "`get_report_profit_and_loss` (look for an 'Exchange Gain or Loss' account), `list_bill` / `list_invoice` (Balance > '0') with CurrencyRef and ExchangeRate, `list_exchange_rate`; `get_preferences` CurrencyPrefs.MultiCurrencyEnabled",
    dates: 'Preset `this_fy_td` for realised gains; unrealised is as of today.',
    fileName: 'quickbooks-exchange-gains-losses.html', tags: ['quickbooks', 'multicurrency', 'fx'],
    members: [['Realised Exchange Gains & Losses', 'Report = Realised — from the exchange gain/loss account on the Profit and Loss'], ['Unrealised Exchange Gains & Losses', 'Report = Unrealised (estimate) — open foreign-currency documents revalued at current rates'], ['Realised by transaction and currency', 'N/A — QuickBooks\' realised report is not in the Accounting API']],
    checks: ['Unrealised by currency sums to the total', 'Every open foreign-currency document has a current rate', 'Realised = FX accounts on the Profit and Loss (information)'],
    golden: 'A/P in USD / EUR / GBP / PHP / PLN exists in the sample company — compare the unrealised estimate with QuickBooks\' Unrealised Gains & Losses report.' },
  { id: 'custom', q: 'Q35', skill: 'quickbooks-custom-report-builder', title: 'Custom report builder', menu: 'Reports › Standard reports › Custom report builder', wave: 'Wave 3 (Train 06)', custom: true,
    trigger: "the user asks for a QuickBooks report that no other skill covers, a custom report, or a specific QuickBooks standard report by name (for example Sales by Class, Sales by Location, Customer Balance Detail, Supplier Balance Detail, Transaction List, Profit and Loss Detail)",
    discovery: 'The chosen `get_report_*` tool with the period and basis — note whether Rows contain Sections (statement layout) or only Data rows (list layout)',
    dates: 'Preset `this_fy_td` unless the user names a period.',
    fileName: 'quickbooks-custom-report.html', tags: ['quickbooks', 'custom-report'],
    members: [['Any of the 30 QuickBooks report tools', 'Set the binding tool, `tools.custom_report`, `title` and `fileName` for the chosen report (list below)'], ['Revenue Recognition (Beta), Bill Approval Status, Invoice Approval Status', 'N/A — not in the Accounting API'], ['Product/Item Profitability by Customer', 'Use get_report_item_sales with Display columns by Customers']],
    checks: ["Each 'Total for' = Σ its rows (statement layout) or TOTAL row = Σ rows (list layout)", 'QuickBooks returned the requested period'],
    golden: 'User-defined — compare with the same QuickBooks report and controls.' },
  { id: 'audit-log', q: 'Q21', skill: 'quickbooks-audit-log', title: 'Audit Log', menu: 'Reports › Standard reports › Business overview › Audit Log', wave: 'Wave 3 (Train 06)', static: 'export',
    trigger: 'the user asks for the audit log, who changed what, recent edits or deletions, user activity, or attaches a QuickBooks Audit Log export',
    discovery: 'None — the Audit Log is not in the Accounting API. The user attaches the export.',
    dates: 'The period in the export.',
    fileName: 'quickbooks-audit-log.html', tags: ['quickbooks', 'audit-log', 'export'],
    members: [['Audit Log', 'From the attached export: events by type and user, filters by user, event type, date and text'], ['Intuit Intelligence Audit Log', 'N/A — not in the export']],
    checks: ['Counts by event type sum to the events shown'],
    golden: "'10 Sept, 9:24 am — Melanie Burrows — Added Bill Payment (Cheque) to Yucheng Sun - USD for $1000.00'; system rows 'Online Banking Administration — Manually updated Online Banking accounts for Wise Business'." },
  { id: 'ask', q: 'Q37', skill: 'quickbooks-ask-a-question', title: 'Ask a question', menu: 'Reports › Ask a question (BETA)', wave: 'Wave 3 (Train 06)', static: 'guide',
    trigger: 'the user asks a plain-English question about their QuickBooks figures, such as how much was spent on something, who owes the most, what net profit was, or what the bank balance is',
    discovery: 'The one tool that answers the question (routing table below).', dates: 'Resolve the period from the question and the company financial year.',
    fileName: '', tags: [],
    members: [['Ask a question', 'Answer in chat with the figure, period, basis and source; offer the full live report'], ['Intuit Intelligence assistants', 'N/A — the QuickBooks Reporting Specialist is the equivalent']],
    checks: ['Answer figures tie to the underlying report (the answer names the report line or lines used)'],
    golden: "'What was net profit in August?' → Net Earnings −A$175,286.75 (Profit and Loss, August 2026, accrual)." }
];
