// Wave 2 (F4) family metadata — appended to families.js.
module.exports = [
  { id: 'client-overview', q: 'Q16', skill: 'quickbooks-client-overview', title: 'Client overview (accountant-only)', menu: 'All apps › Accounting › Client overview', wave: 'Wave 2 (Train 03)',
    trigger: 'the user (an accountant or bookkeeper) asks for the client overview, a books health check, common issues, undeposited funds, uncategorised transactions, negative accounts, opening balance equity or transaction volume',
    discovery: '`list_account` (Active = true) — expect `QueryResponse.Account[]` with Name, AccountType, AccountSubType, Classification and CurrentBalance; plus both ageing reports and `get_report_transaction_list` for the last 30 days',
    dates: 'No manual dates: the transaction-volume window (last 30 days) is set on every open.',
    fileName: 'quickbooks-client-overview.html', tags: ['quickbooks', 'accountant', 'books-review'],
    members: [['Banking activity', "'In QuickBooks' balances per bank and card account; bank balance, unaccepted, unreconciled and reconciled-through are N/A (not in the Accounting API)"], ['Common issues', 'Undeposited funds, uncategorised asset/income/expense, A/R and A/P ageing over 90 days, opening balance equity, negative asset and liability accounts (owed liabilities, contra assets and GST/BAS accounts are normal), GST / BAS payable and suspense balances'], ['Transaction volume', 'Last 30 days by transaction type'], ['Books review, Prep for taxes', 'N/A — QuickBooks Accountant workflows']],
    checks: ['A/P ageing over 90 days = A/P ageing report 91-and-over band', 'A/R ageing over 90 days = A/R ageing report 91-and-over band', 'Transaction volume = Σ by type', 'Unreconciled counts equal bank-feed queries (N/A — not in the API)'],
    golden: "Banking: Wise-AUD A$145,221.70 in QuickBooks · ANZ A$99.00 · Doug's Amex A$16,708.64. Common issues: A/P ageing over 90 days −A$46,500.00 (10 transactions); negative asset/liability accounts 2." },
  { id: 'gl', q: 'Q23', skill: 'quickbooks-general-ledger', title: 'General Ledger and transaction-list family', menu: 'Reports › Standard reports › For my accountant', wave: 'Wave 2 (Train 03)',
    trigger: 'the user asks for the general ledger, GL, ledger detail for an account, the journal report, a transaction list by date, the account list or the chart of accounts',
    discovery: "`get_report_general_ledger` with `start_date`, `end_date`, `accounting_method` — expect one section per account whose Rows start with a 'Beginning Balance' Data row, columns Date | Transaction Type | Num | Name | Memo/Description | Split | Amount | Balance, and a 'Total for <account>' Summary",
    dates: 'Preset `last_month`. Keep General Ledger periods to a month or a quarter — large periods return many rows.',
    fileName: 'quickbooks-general-ledger.html', tags: ['quickbooks', 'general-ledger', 'accountant'],
    members: [['General Ledger', 'Report = General Ledger'], ['General Ledger Summary', 'Report = General Ledger Summary (beginning, net movement, ending per account)'], ['Journal', 'Report = Journal (get_report_journal_report)'], ['Transaction List by Date', 'Report = Transaction List by Date'], ['Account List', 'Report = Account List'], ['Adjusting Journal Entries, Recent / Recent Automatic Transactions, Recurring Template List, Invalid Journal Entries, Uncoded Transactions, Reconciliation Reports, Transaction List with Splits, Transaction Detail by Account', 'N/A or later members — not exposed as Accounting API reports']],
    checks: ['Balance = beginning + Σ amounts (every account)', "'Total for <account>' amount = Σ its transactions", 'Journal: Σ debits = Σ credits (Journal view)'],
    golden: 'PHP Bank: opening −A$8.52 → closing −A$2.69; loan payments to the Philippines Branch Office; Wise transfers.' },
  { id: 'sales', q: 'Q25', skill: 'quickbooks-sales-and-customers', title: 'Sales and customers family', menu: 'Reports › Standard reports › Sales and customers', wave: 'Wave 2 (Train 03)',
    trigger: 'the user asks for sales by customer, sales by product or service, income by customer, top customers, product mix, the customer contact list, the product/service list or quotes by customer',
    discovery: '`get_report_customer_sales` with `start_date`, `end_date`, `accounting_method` — expect one Data row per customer and a GrandTotal TOTAL row; `get_report_item_sales` has columns including Quantity and Amount',
    dates: 'Preset `this_fy_td`: `start_date` = FY start, `end_date` = `"today"`.',
    fileName: 'quickbooks-sales-and-customers.html', tags: ['quickbooks', 'sales', 'customers'],
    members: [['Sales by Customer Summary', 'Report = Sales by Customer Summary'], ['Sales by Product/Service Summary', 'Report = Sales by Product/Service Summary'], ['Income by Customer Summary', 'Report = Income by Customer Summary'], ['Customer Contact List', 'Report = Customer Contact List'], ['Product/Service List', 'Report = Product/Service List'], ['Quotes by Customer', 'Report = Quotes by Customer'], ['Detail variants, Deposit Detail, Quotes & Progress Invoicing, Sales by Customer Type, Payment Method List, Time Activities by Customer, Transaction List by Customer / Tag Group, Cashflow Payment Transactions', 'Later members (tag groups are not in the API)']],
    checks: ['Σ customers = sales total', 'Σ customers = income for the period (P&L Total for Income; a difference means income not raised on a sales form)', 'Σ products/services = sales total'],
    golden: "Income A$72,532 (from the homepage) — Sales by Customer should tie to the period's sales income." },
  { id: 'expenses', q: 'Q27', skill: 'quickbooks-expenses-and-suppliers', title: 'Expenses and suppliers family', menu: 'Reports › Standard reports › Expenses and suppliers', wave: 'Wave 2 (Train 03)',
    trigger: 'the user asks for expenses by supplier, top suppliers, supplier concentration, a purchase list, cheque detail or the supplier contact list',
    discovery: '`get_report_vendor_expenses` with `start_date`, `end_date`, `accounting_method` — expect one Data row per supplier and a GrandTotal TOTAL row',
    dates: 'Preset `this_fy_td`.',
    fileName: 'quickbooks-expenses-and-suppliers.html', tags: ['quickbooks', 'expenses', 'suppliers'],
    members: [['Expenses by Supplier Summary', 'Report = Expenses by Supplier Summary (with share of total and concentration)'], ['Purchase List', 'Report = Purchase List (expenses, cheques, credit-card expenses and bills in the period)'], ['Cheque Detail', 'Report = Cheque Detail'], ['Supplier Contact List', 'Report = Supplier Contact List'], ['Purchases by Supplier / Product Detail, Transaction List by Supplier, Supplier Phone List', 'Later members']],
    checks: ['Σ suppliers = supplier expense total', 'Σ suppliers = expenses for the period (Cost of Sales + Expenses + Other Expenses; a difference means expenses with no supplier)'],
    golden: 'Top supplier concentration led by Adaptovate (see the Expenses & Pay Bills overview).' },
  { id: 'business-feed', q: 'Q01', skill: 'quickbooks-business-feed', title: 'Business feed', menu: 'Feed › Business feed', wave: 'Wave 2 (Train 04)',
    trigger: "the user asks for the business feed, what's new in the business, a 'report ready' summary of last month, or quick insights on profit, spending, money owed and bills",
    discovery: '`get_report_profit_and_loss` by Month for the last six complete months; both ageing reports',
    dates: 'No manual dates: the six-month window is set on every open.',
    fileName: 'quickbooks-business-feed.html', tags: ['quickbooks', 'feed', 'insights'],
    members: [['Report ready — Profit and Loss card', 'Net profit, income and expenses for last month with a net-profit sparkline'], ['Insight cards', 'Net profit vs the month before, biggest expense change, money owed to you, bills to pay — worded from the figures only'], ['Intuit Intelligence assistants, Ask a question', 'N/A — use mySidekick or the QuickBooks Reporting Specialist']],
    checks: ['Card figures equal the P&L for the same month (net = income − cost of sales − expenses − other expenses)', 'Monthly columns sum to the P&L total'],
    golden: "'Report ready' card: Net profit from August −A$175,286.75 with income and expense lines." },
  { id: 'budgets', q: 'Q08', skill: 'quickbooks-budgets', title: 'Budgets (Budget vs Actuals)', menu: 'Reports › Financial planning › Budgets', wave: 'Wave 2 (Train 04)',
    trigger: 'the user asks for budget vs actuals, a budget report, the budget overview, profit and loss budget performance, or how the business is tracking against budget',
    discovery: "`list_budget` — expect `QueryResponse.Budget[]` with Name, StartDate, EndDate, BudgetType ProfitAndLoss and BudgetDetail[] {BudgetDate, Amount, AccountRef}; then `get_report_profit_and_loss` by Month for that budget's dates",
    dates: "Set `start_date` / `end_date` to the chosen budget's StartDate / EndDate (default: the budget covering today). The page follows the budget the reader selects.",
    fileName: 'quickbooks-budget-vs-actuals.html', tags: ['quickbooks', 'budget', 'planning'],
    members: [['Budget vs Actuals', 'Report = Budget vs Actuals (Actual | Budget | Over budget | % of budget)'], ['Budget Overview', 'Report = Budget Overview (account × month grid)'], ['Profit and Loss Budget Performance', 'Report = P&L Budget Performance (this month and year to date)'], ['Create a budget, Import budget', 'N/A — the connector reads budgets but does not create them']],
    checks: ['Actual = Profit and Loss (each account, budget period)', 'Σ months = annual budget (each account and in total)'],
    golden: 'No budget in the sample company (empty state captured) — the report says so and points to QuickBooks › Budgets.' },
  { id: 'expenses-overview', q: 'Q10', skill: 'quickbooks-expenses-overview', title: 'Expenses & Pay Bills overview', menu: 'All apps › Expenses & Pay Bills › Overview', wave: 'Wave 2 (Train 04)',
    trigger: 'the user asks for the expenses overview, bills to pay, unpaid or overdue bills, spend over time, spend by supplier this month, or days payable outstanding (DPO)',
    discovery: "`list_bill` (Balance > '0'), `list_bill_payment`, `get_report_aged_payables`, `get_report_profit_and_loss` by Month and `get_report_vendor_expenses`",
    dates: 'No manual dates: last quarter + this quarter (spend chart) and this month (spend insights) are set on every open.',
    fileName: 'quickbooks-expenses-overview.html', tags: ['quickbooks', 'expenses', 'bills', 'dashboard'],
    members: [['Bills funnel', 'For review (N/A — bill inbox not in the API) · Unpaid (with overdue count) · Paid (last 30 days)'], ['Spend over time', 'This quarter vs last quarter, by month'], ['Spend insights', 'Supplier shares this month'], ['DPO tile', 'A/P ÷ spend × days'], ['Create actions', 'N/A — use QuickBooks']],
    checks: ['Unpaid bills = A/P ageing total', 'Paid = bill payments in the last 30 days (information)', 'Spend insights total = Σ suppliers'],
    golden: 'Unpaid A$80,932.81 (4 overdue) · Paid A$15,012.95 (10 bills) · Spend Q3 2026 A$565,789.63 · September A$312,081.07.' },
  { id: 'sales-overview', q: 'Q11', skill: 'quickbooks-sales-overview', title: 'Sales & Get Paid overview', menu: 'All apps › Sales & Get Paid › Overview', wave: 'Wave 2 (Train 04)',
    trigger: 'the user asks for the sales overview, income over time, unpaid or overdue invoices, payments received, not-deposited payments, or days sales outstanding (DSO)',
    discovery: "`get_report_profit_and_loss` by Month (income), `list_invoice` (Balance > '0'), `list_payment`, `get_report_aged_receivables`",
    dates: 'No manual dates: the 12-month (or 30-day) window and the previous-year window are set on every open.',
    fileName: 'quickbooks-sales-overview.html', tags: ['quickbooks', 'sales', 'invoices', 'dashboard'],
    members: [['Income over time', 'Last 365 days or last 30 days, compare to previous year'], ['Invoices funnel', 'Unpaid (overdue / not due yet) · Paid (not deposited / deposited)'], ['DSO tile', 'A/R ÷ income × days'], ['Quick actions', 'N/A — use QuickBooks']],
    checks: ['Unpaid = A/R ageing total', 'Paid = payments received in the period (information)', 'Income chart months sum to the period income'],
    golden: 'Income over time A$27,500.03 last quarter · Unpaid A$39,105 (overdue A$0, not due yet A$39,105) · Paid A$92,400 (not deposited A$0, deposited A$92,400).' },
  { id: 'catalogue', q: 'Q02', skill: 'quickbooks-reports-catalogue', title: 'Reports catalogue', menu: 'Reports › Standard reports', wave: 'Wave 2 (Train 04)',
    trigger: 'the user asks what QuickBooks reports are available, for the reports list or catalogue, which reports the agent can build, or to search for a report by name',
    discovery: '`qbo_query` (`SELECT * FROM CompanyInfo`) and `get_preferences` — only the company name, country and home currency are shown; the catalogue itself is built into the config',
    dates: 'None.',
    fileName: 'quickbooks-reports-catalogue.html', tags: ['quickbooks', 'catalogue', 'library'],
    members: [['Every QuickBooks report family (Q00–Q39) as a card', 'Name, plain-English description, Live or Not yet implemented · Wave N, grouped by category'], ['Search and category chips', 'Filter by name, description or Q-ID; one chip per category'], ['Favourites, Create new report', 'Use saved reports in the Reports library; the custom report builder (Q35) builds any standard report']],
    checks: ['Every report maps to a family prompt (Q00–Q39)'],
    golden: 'Same layout as the Xero Reports Catalog: company header, search, category chips, cards marked Live or Not yet implemented.' }
];
