XK.app({
  title: 'Xero · Financial Overview', primary: 'pnl', dated: ['pnl', 'pnl_cash', 'bank', 'tb'], org: 'org', conns: 'connections',
  inputs: { start: 'from_date', end: 'to_date', basis: 'basis', org: 'org', display: 'display' },
  defaults: { from_date: '2026-07-01', to_date: '2026-09-25', prior_from: '2025-07-01', prior_to: '2025-09-25', basis: 'Accrual', org: '', page: 1,
    display: '{"cents":1,"k":0,"zeros":0,"neg":"paren","red":1,"hdr":1,"ftr":1,"style":"mysmb","dens":"100","p":"this_fy_td","a":"custom","c":"none","v":""}' },
  uses: { pnl: ['from_date', 'to_date', 'org'], pnl_cash: ['from_date', 'to_date', 'org'], pnl_ly: ['prior_from', 'prior_to', 'org'], pnl_ly_cash: ['prior_from', 'prior_to', 'org'], bank: ['from_date', 'to_date', 'org'], tb: ['to_date', 'org'], tb_now: ['org'], invoices: ['org'], credit_notes: ['org'], overpayments: ['org'], org: ['org', 'basis'], connections: [] },
  paged: { invoices: { input: 'page', key: 'Invoices' }, credit_notes: { input: 'page', key: 'CreditNotes' }, overpayments: { input: 'page', key: 'Overpayments' } },
  // monthly trend: the calendar months of the period (latest 12), or the 12 months ending with the period when it is one month or less
  fan: {
    pnl: function (inp) { if (inp.basis === 'Cash') return []; var s = inp.from_date, e = inp.to_date, n = (+e.slice(0, 4) - +s.slice(0, 4)) * 12 + (+e.slice(5, 7) - +s.slice(5, 7)) + 1, inP = n >= 2; return XK.monthsEnding(e, inP ? Math.min(n, 12) : 12).map(function (m) { return { key: m.key, inputs: { from_date: inP && m.start < s ? s : m.start, to_date: m.end > e ? e : m.end } }; }); },
    pnl_cash: function (inp) { return inp.basis === 'Cash' ? this.pnl(Object.assign({}, inp, { basis: 'Accrual' })) : []; } // the same months on the cash basis
  },
  tools: { pnl: 'get_profit_and_loss (period and months, accrual)', pnl_cash: 'get_profit_and_loss (period and months, cash)', pnl_ly: 'get_profit_and_loss (last year, accrual)', pnl_ly_cash: 'get_profit_and_loss (last year, cash)', bank: 'get_bank_summary (period end)', tb: 'get_trial_balance (period end)', tb_now: 'get_trial_balance (today)', invoices: 'list_invoices (awaiting payment)', credit_notes: 'list_credit_notes', overpayments: 'list_overpayments', org: 'get_organisation', connections: 'list_connections' },
  presets: [['this_month', 'This month'], ['last_month', 'Last month'], ['this_quarter', 'This quarter'], ['last_quarter', 'Last quarter'], ['this_fy_td', 'This financial year to date'], ['this_fy', 'This financial year'], ['last_fy', 'Last financial year'], ['last_12m', 'Last 12 months'], ['custom', 'Custom']],
  derive: function (inp) { var y = function (s) { var p = s.split('-'), yy = +p[0] - 1, last = XK.eom(yy, +p[1]).getUTCDate(); return yy + '-' + p[1] + '-' + String(Math.min(+p[2], last)).padStart(2, '0'); }; return { prior_from: y(inp.from_date), prior_to: y(inp.to_date) }; },
  render: function (c) {
    var body = c.body, money = function (v) { return XK.money(v, c.currency, c.display); }, r2 = function (v) { return Math.round(v * 100) / 100; }, cash = c.inputs.basis === 'Cash', B = cash ? '_cash' : '';
    var from = c.inputs.from_date, to = c.inputs.to_date, id = 'pnl' + B, idLy = 'pnl_ly' + B;
    if (c.errors[id]) { body.innerHTML = '<p class="xk-err">' + XK.h(c.err(id)) + '</p>'; return { checks: [{ name: 'Profit and Loss loaded', pass: false, detail: c.err(id) }] }; }
    if (!c.data[id]) return {};
    var w = XK.walk(c.data[id]), wl = c.data[idLy] ? XK.walk(c.data[idLy]) : null, P = XK.plParts(w), Q = wl ? XK.plParts(wl) : null;
    var K = function (p) { return p ? { rev: p.trading, gp: p.gp, np: p.np, gpm: p.trading ? p.gp / p.trading : null, npm: p.trading ? p.np / p.trading : null } : null; }, k = K(P), kl = K(Q);
    var chg = function (a, b) { return a == null || b == null || !b ? null : (a - b) / Math.abs(b); };
    var lyTxt = function (key, isPct) { if (!kl) return 'Last year: N/A — ' + (c.err(idLy) || 'not in source'); var v = kl[key]; return 'Last year: ' + (v == null ? 'N/A' : isPct ? XK.pct(v) : money(v)) + (v == null || k[key] == null ? '' : ' · change ' + (isPct ? (((k[key] - v) * 100).toFixed(1) + ' pts') : money(r2(k[key] - v)))); };
    var kp = [{ label: 'Revenue', value: k.rev, delta: kl && chg(k.rev, kl.rev), sub: lyTxt('rev') }, { label: 'Gross profit', value: k.gp, delta: kl && chg(k.gp, kl.gp), sub: lyTxt('gp') }, { label: 'Gross margin %', text: k.gpm == null ? 'N/A' : XK.pct(k.gpm), sub: lyTxt('gpm', true) },
      { label: 'Net profit', value: k.np, delta: kl && chg(k.np, kl.np), sub: lyTxt('np') }, { label: 'Net margin %', text: k.npm == null ? 'N/A' : XK.pct(k.npm), sub: lyTxt('npm', true) }];
    // trend (fan: one Profit and Loss per month)
    var fz = c.fan(id), trend = fz ? fz.map(function (it) { if (it.error || !it.value) return { key: it.key, error: it.error || 'no data' }; var p = XK.plParts(XK.walk(it.value)); return { key: it.key, rev: p.trading, np: p.np }; }) : null, trendOk = trend && trend.every(function (m) { return !m.error; });
    var nM = (+to.slice(0, 4) - +from.slice(0, 4)) * 12 + (+to.slice(5, 7) - +from.slice(5, 7)) + 1;
    // bank balances at the period end (Bank Summary: Opening | Cash Received | Cash Spent | Closing)
    var bw = c.data.bank ? XK.walk(c.data.bank) : null, banks = bw ? bw.lines.filter(function (l) { return l.kind === 'row'; }).map(function (l) { return { name: l.label, id: l.id, close: l.values[3] }; }) : [], bTot = bw ? bw.lines.filter(function (l) { return l.kind === 'total' && /^total$/i.test(l.label); })[0] : null;
    // ageing as at the date of the Trial Balance "today" (open documents; credit notes and overpayments negative, as in Xero)
    var tbN = c.data.tb_now ? XK.tbYtd(c.data.tb_now) : null, tbNDate = c.data.tb_now ? XK.titleDates(XK.walk(c.data.tb_now).titles.slice(2).join(' '))[0] : null, asAt = tbNDate || c.today;
    var labels = ['Current', '1–30 days', '31–60 days', '61–90 days', '90+ days'], bucket = function (x) { var d = Math.round((Date.parse(asAt) - Date.parse(x.due || x.date)) / 864e5); return d <= 0 ? 0 : d <= 30 ? 1 : d <= 60 ? 2 : d <= 90 ? 3 : 4; }; // by due date, as Xero's aged reports
    var side = function (t) { var d = XK.openDocs({ invoices: c.rows('invoices'), credit_notes: c.rows('credit_notes'), overpayments: c.rows('overpayments'), types: t }, c.currency, asAt), b = [0, 0, 0, 0, 0], by = {}; d.forEach(function (x) { var j = bucket(x); b[j] = r2(b[j] + x.amount); by[x.contact] = r2((by[x.contact] || 0) + x.amount); }); return { docs: d, b: b, total: XK.sum(d.map(function (x) { return x.amount; })), top: Object.keys(by).map(function (n) { return { name: n, total: by[n] }; }).sort(function (a, z) { return z.total - a.total; }).slice(0, 5) }; };
    var AR = side({ invoices: 'ACCREC', credit_notes: 'ACCRECCREDIT', overpayments: 'RECEIVE-OVERPAYMENT' }), AP = side({ invoices: 'ACCPAY', credit_notes: 'ACCPAYCREDIT', overpayments: 'SPEND-OVERPAYMENT' });
    var agRow = function (name, s) { var o = { name: name, total: s.total }; s.b.forEach(function (v, j) { o['b' + j] = v; }); return o; }, docsErr = ['invoices', 'credit_notes', 'overpayments'].filter(function (x) { return c.errors[x]; })[0];
    body.innerHTML = XK.kpis(kp, c) +
      '<div class="xk-card" style="margin-top:16px"><h3>Monthly revenue and net profit' + (nM >= 2 ? '' : ' — the 12 months to ' + XK.shortDate(to)) + '</h3>' + (trend == null ? '<p class="muted">' + (c.live ? 'Loading the months…' : 'N/A in a snapshot — open the live report') + '</p>' : trendOk ? '<div id="fo-trend"></div>' : '<p class="xk-err">Some months could not be loaded: ' + XK.h(trend.filter(function (m) { return m.error; }).map(function (m) { return XK.monthLabel(m.key) + ' (' + m.error + ')'; }).join('; ')) + '</p>') + '</div>' +
      '<div class="xk-grid2" style="margin-top:16px"><div class="xk-card"><h3>Bank balances at ' + XK.h(XK.shortDate(to)) + '</h3>' + (bw ? '<div id="fo-bank"></div>' : '<p class="xk-err">' + XK.h(c.err('bank') || 'Bank Summary unavailable') + '</p>') + '</div>' +
      '<div class="xk-card"><h3>Receivables and payables ageing — as at ' + XK.h(XK.shortDate(asAt)) + ' (today)</h3>' + (docsErr ? '<p class="xk-err">' + XK.h(c.err(docsErr)) + '</p>' : '<div id="fo-age"></div><div class="xk-grid2"><div><h3>Top 5 customers owing</h3><div id="fo-tar"></div></div><div><h3>Top 5 suppliers to pay</h3><div id="fo-tap"></div></div></div>') + '</div></div>';
    if (trendOk) XK.bars(document.getElementById('fo-trend'), { title: 'Monthly revenue and net profit', labels: trend.map(function (m) { return XK.monthLabel(m.key); }), series: [{ name: 'Revenue', values: trend.map(function (m) { return m.rev; }) }, { name: 'Net profit', values: trend.map(function (m) { return m.np; }) }] }, c);
    if (bw) XK.grid(document.getElementById('fo-bank'), { rows: banks, columns: [{ key: 'name', title: 'Bank account' }, { key: 'close', title: 'Balance', money: true }], total: { name: 'Total', close: bTot ? bTot.values[3] : null }, empty: 'No bank accounts.' }, c);
    if (!docsErr) {
      XK.grid(document.getElementById('fo-age'), { rows: [agRow('Receivables', AR), agRow('Payables', AP)], columns: [{ key: 'name', title: '' }].concat(labels.map(function (x, j) { return { key: 'b' + j, title: x, money: true }; })).concat([{ key: 'total', title: 'Total', money: true }]) }, c);
      var top = function (el, s) { XK.grid(document.getElementById(el), { rows: s.top.map(function (x) { return { name: x.name, total: x.total }; }), columns: [{ key: 'name', title: 'Contact' }, { key: 'total', title: 'Outstanding', money: true }], empty: 'Nothing outstanding.' }, c); };
      top('fo-tar', AR); top('fo-tap', AP);
    }
    // ---- checks
    var lt = XK.linesTies(w.lines), rt = XK.runningTies(w), gpOk = XK.near(P.gp, r2(P.trading - P.cos)), npOk = XK.near(P.np, r2(P.gp + P.otherIncome - P.opex - P.otherExpenses));
    var lyD = wl ? XK.titleDates((wl.titles || []).slice(2).join(' ')) : [], lyOk = wl && lyD[0] === c.inputs.prior_from && lyD[lyD.length - 1] === c.inputs.prior_to, lyT = wl ? XK.runningTies(wl) : null;
    var tbT = c.data.tb ? XK.tbYtd(c.data.tb) : null, fyS = XK.fyStartOf(to, c.fy.month), npTie = !cash && from === fyS;
    var tSum = trendOk ? { rev: XK.sum(trend.map(function (m) { return m.rev; })), np: XK.sum(trend.map(function (m) { return m.np; })) } : null, tLast = trendOk ? trend[trend.length - 1] : null;
    var trendCheck = trend == null ? { name: 'Monthly trend = the period\'s Profit and Loss', pass: null, detail: c.live ? 'Loading' : 'N/A in a snapshot' } : !trendOk ? { name: 'Monthly trend loaded', pass: false, detail: 'Some months failed to load' }
      : nM >= 2 && nM <= 12 ? { name: 'Σ monthly revenue and net profit = the period\'s Profit and Loss (' + trend.length + ' monthly reports)', pass: XK.near(tSum.rev, P.trading) && XK.near(tSum.np, P.np), detail: money(tSum.rev) + ' vs ' + money(P.trading) + ' · ' + money(tSum.np) + ' vs ' + money(P.np) }
      : nM === 1 && from.slice(8) === '01' ? { name: 'The period\'s month in the trend = the period\'s Profit and Loss', pass: XK.near(tLast.rev, P.trading) && XK.near(tLast.np, P.np), detail: money(tLast.rev) + ' vs ' + money(P.trading) }
      : { name: 'Monthly trend vs the period', pass: null, info: true, detail: nM > 12 ? 'The trend shows the latest 12 of ' + nM + ' months' : 'The period is part of a month' };
    var tbBank = tbT && banks.length && banks.every(function (b) { return b.id && tbT.bal(b.id) != null; }) ? XK.sum(banks.map(function (b) { return tbT.bal(b.id); })) : null, bankSum = XK.sum(banks.map(function (b) { return b.close; }));
    var arTB = tbN ? tbN.named(/^accounts receivable$/i) : null, apTB = tbN ? tbN.named(/^accounts payable$/i) : null; if (apTB != null) apTB = -apTB;
    var trunc = ['invoices', 'credit_notes', 'overpayments'].filter(function (x) { return c.truncated(x); });
    var ageTie = function (nm, s, tbv, acc) { return docsErr || !tbN ? { name: nm + ' ageing total = ' + acc + ' on the Trial Balance at ' + asAt, pass: null, detail: c.err(docsErr) || c.err('tb_now') } : { name: nm + ' ageing total = ' + acc + ' on the Trial Balance at ' + asAt + ' (a separate Xero report)', pass: XK.near(s.total, tbv == null ? 0 : tbv), detail: money(s.total) + ' vs ' + (tbv == null ? 'no ' + acc + ' row ($0.00)' : money(tbv)) + (XK.near(s.total, tbv == null ? 0 : tbv) ? '' : ' — unallocated prepayments are not loaded') }; };
    var checks = [
      { name: 'Profit and Loss: section totals = Σ accounts; Gross / Net Profit = running total', pass: lt.failed.length === 0 && rt.failed.length === 0, detail: lt.failed.concat(rt.failed).join('; ') || lt.checked + ' totals, ' + rt.checked + ' computed lines' },
      { name: 'Gross profit = Revenue − Cost of sales; Net profit = Gross profit + Other income − Expenses', pass: gpOk && npOk, detail: money(P.trading) + ' − ' + money(P.cos) + ' = ' + money(P.gp) + ' · NP ' + money(P.np) },
      !wl ? { name: 'Last year: Profit and Loss for ' + c.inputs.prior_from + ' to ' + c.inputs.prior_to, pass: false, detail: c.err(idLy) || 'not loaded' } : { name: 'Last year = a Profit and Loss for exactly ' + c.inputs.prior_from + ' to ' + c.inputs.prior_to + ', and its own totals tie', pass: !!lyOk && lyT.failed.length === 0, detail: 'Xero title: ' + (wl.titles || []).slice(2).join(' ') + (lyT.failed.length ? ' · ' + lyT.failed.join('; ') : '') },
      npTie ? { name: 'Net profit = income − expenses for the financial year on the Trial Balance at ' + to, pass: tbT ? XK.near(P.np, tbT.net) : null, detail: tbT ? money(P.np) + ' vs ' + money(tbT.net) : c.err('tb') } : { name: 'Net profit vs the Trial Balance', pass: null, info: true, detail: cash ? 'The Trial Balance is accrual — no tie on the cash basis' : 'Ties only when the period starts at the financial-year start (' + fyS + ')' },
      trendCheck,
      { name: 'Bank balances: Σ accounts = the Bank Summary total = the same accounts on the Trial Balance at ' + to, pass: bw && tbT ? !!bTot && XK.near(bankSum, bTot.values[3]) && tbBank != null && XK.near(bankSum, tbBank) : null, detail: bw && tbT ? money(bankSum) + ' vs ' + (bTot ? money(bTot.values[3]) : 'no total') + ' vs ' + (tbBank == null ? 'N/A — not on the Trial Balance' : money(tbBank)) : c.err('bank') || c.err('tb') },
      ageTie('Receivables', AR, arTB, 'Accounts Receivable'), ageTie('Payables', AP, apTB, 'Accounts Payable'),
      { name: 'All open documents loaded', pass: docsErr ? false : !trunc.length, detail: trunc.length ? 'May be truncated (over 20 pages): ' + trunc.join(', ') : c.rows('invoices').length + ' invoice(s) and bill(s), ' + c.rows('credit_notes').length + ' credit note(s), ' + c.rows('overpayments').length + ' overpayment(s)' }
    ];
    this._x = { kp: [['Revenue', k.rev, kl && kl.rev], ['Gross profit', k.gp, kl && kl.gp], ['Gross margin %', k.gpm, kl && kl.gpm, 1], ['Net profit', k.np, kl && kl.np], ['Net margin %', k.npm, kl && kl.npm, 1]], trend: trendOk ? trend : null, banks: banks, bTot: bTot ? bTot.values[3] : null, AR: AR, AP: AP, labels: labels, asAt: asAt };
    return { checks: checks, period: XK.periodLine(from, to) + ' · ' + c.inputs.basis + ' basis',
      notes: ['Revenue = the Income section of Xero\'s Profit and Loss; gross and net profit are Xero\'s own lines; margins ÷ revenue. Last year = a separate P&L for the same dates a year earlier.', 'Bank balances: Bank Summary closing balances, tied to the Trial Balance at the exact period end (Xero\'s Balance Sheet is only at month ends).', 'Ageing is today\'s position by due date, tied to today\'s Trial Balance. Unallocated prepayments are not loaded.'],
      na: ['Bank statement balances (no bank-feed data in the Xero API)', 'Ageing at a past date (the Xero API lists what is open today)'] };
  },
  excel: function (c) {
    var x = this._x; if (!x) return [];
    var head = function (name) { return [[{ v: c.company || 'N/A — not in source', s: 'title' }], [{ v: name, s: 'bold' }], [XK.periodLine(c.inputs.from_date, c.inputs.to_date)], []]; }, b = function (a) { return a.map(function (t) { return { v: t, s: 'bold' }; }); }, mv = function (v, p) { return v == null ? 'N/A' : { v: v, s: p ? 'pct' : 'money' }; };
    var k = head('Financial overview').concat([b(['Metric', 'This period', 'Last year', 'Change'])]).concat(x.kp.map(function (r) { return [r[0], mv(r[1], r[3]), mv(r[2], r[3]), r[1] == null || r[2] == null ? 'N/A' : mv(Math.round((r[1] - r[2]) * (r[3] ? 10000 : 100)) / (r[3] ? 10000 : 100), r[3])]; }));
    var t = head('Monthly trend').concat([b(['Month', 'Revenue', 'Net profit'])]).concat(x.trend ? x.trend.map(function (m) { return [XK.monthLabel(m.key), mv(m.rev), mv(m.np)]; }) : [['N/A — the monthly trend needs the live report']]);
    var bk = head('Bank balances').concat([b(['Bank account', 'Balance'])]).concat(x.banks.map(function (r) { return [r.name, mv(r.close)]; })).concat([[{ v: 'Total', s: 'bold' }, x.bTot == null ? 'N/A' : { v: x.bTot, s: 'moneyBold' }]]);
    var ag = head('Ageing as at ' + x.asAt).concat([b([''].concat(x.labels, ['Total']))]).concat([['Receivables', x.AR], ['Payables', x.AP]].map(function (r) { return [r[0]].concat(r[1].b.map(function (v) { return mv(v); }), [{ v: r[1].total, s: 'moneyBold' }]); }))
      .concat([[], b(['Top customers owing', 'Outstanding'])]).concat(x.AR.top.map(function (r) { return [r.name, mv(r.total)]; })).concat([[], b(['Top suppliers to pay', 'Outstanding'])]).concat(x.AP.top.map(function (r) { return [r.name, mv(r.total)]; }));
    return [{ name: 'Financial overview', rows: k, widths: [30, 18, 18, 18] }, { name: 'Monthly trend', rows: t, widths: [16, 18, 18] }, { name: 'Bank balances', rows: bk, widths: [36, 18] }, { name: 'Ageing', rows: ag, widths: [30, 16, 16, 16, 16, 16, 16] }];
  }
});
