XK.app({
  title: 'Xero · Summary of Tax Amounts by Type', primary: 'bs_end', dated: ['bs_end'], org: 'org', conns: 'connections',
  inputs: { start: 'from_date', end: 'to_date', org: 'org', display: 'display' },
  defaults: { from_date: '2026-04-01', to_date: '2026-06-30', prev_end: '2026-03-31', date_where: 'Date>=DateTime(2026,04,01) AND Date<=DateTime(2026,06,30)', inv_ids: '', org: '', page: 1,
    display: '{"cents":1,"k":0,"zeros":0,"neg":"paren","red":1,"hdr":1,"ftr":1,"style":"mysmb","dens":"100","p":"last_quarter","a":"custom","c":"none","v":"gst","o":"b=org"}' },
  uses: { payments: ['date_where', 'org'], paid_inv: ['inv_ids', 'org'], invoices: ['date_where', 'org'], credit_notes: ['date_where', 'org'], bank_tx: ['date_where', 'org'], tax_rates: ['org'], accounts: ['org'], bs_end: ['to_date', 'org'], bs_start: ['prev_end', 'org'], org: ['org'], connections: [] },
  paged: { payments: { input: 'page', key: 'Payments' }, invoices: { input: 'page', key: 'Invoices' }, credit_notes: { input: 'page', key: 'CreditNotes' }, bank_tx: { input: 'page', key: 'BankTransactions' } },
  sources: { paid_inv: { name: 'Paid invoices', optional: true, quiet: function (i) { return !i.inv_ids; } } },
  // cash basis: the invoices and bills the period's payments paid, 12 ids per call
  fan: { paid_inv: function (inp, c) { var o = ((c.data.org || {}).Organisations || [])[0] || {}, b = c.opt('b'); if (!(b === 'cash' || (b !== 'accrual' && /PAYMENT|CASH/i.test(o.SalesTaxBasis || '')))) return []; var ids = {}; c.rows('payments').forEach(function (p) { var id = (p.Invoice || {}).InvoiceID; if (id && p.Status !== 'DELETED') ids[id] = 1; }); var all = Object.keys(ids), out = []; for (var i = 0; i < all.length; i += 12) out.push({ key: 'b' + i, inputs: { inv_ids: all.slice(i, i + 12).join(',') } }); return out; } },
  tools: { payments: 'list_payments (in the period — cash basis)', paid_inv: 'list_invoices (the invoices and bills those payments paid, by id)', invoices: 'list_invoices (sales invoices and bills in the period, with lines)', credit_notes: 'list_credit_notes (in the period)', bank_tx: 'list_bank_transactions (spend / receive money in the period)', tax_rates: 'list_tax_rates (names and rates)', accounts: 'list_accounts (the GST account)', bs_end: 'get_balance_sheet (GST account at the period end)', bs_start: 'get_balance_sheet (GST account the day before the period)', org: 'get_organisation (GST basis)', connections: 'list_connections' },
  presets: [['this_month', 'This month'], ['last_month', 'Last month'], ['this_quarter', 'This quarter'], ['last_quarter', 'Last quarter'], ['this_fy', 'This financial year'], ['last_fy', 'Last financial year'], ['custom', 'Custom']],
  views: [['gst', 'GST amounts'], ['net', 'Net amounts']],
  options: [{ id: 'b', label: 'GST basis', options: [['org', 'Xero setting'], ['accrual', 'Accrual (invoice)'], ['cash', 'Cash (payments)']], def: 'org' }],
  derive: function (inp) { return { prev_end: XK.addDaysIso(inp.from_date, -1), date_where: XK.dateWhere('Date', inp.from_date, inp.to_date) }; },
  render: function (c) {
    var self = this, body = c.body, money = function (v) { return XK.money(v, c.currency, c.display); }, r2 = function (v) { return Math.round(v * 100) / 100; }, from = c.inputs.from_date, to = c.inputs.to_date;
    var need = ['invoices', 'credit_notes', 'bank_tx', 'tax_rates'].filter(function (id) { return c.errors[id]; });
    if (need.length) { body.innerHTML = '<p class="xk-err">' + XK.h(c.err(need[0])) + '</p>'; return { checks: [{ name: 'Documents and tax rates loaded', pass: false, detail: c.err(need[0]) }] }; }
    if (!c.data.invoices || !c.data.tax_rates) return {};
    // ---- tax lines (the GST Reconciliation / GST Summary data model)
    var org = ((c.data.org || {}).Organisations || [])[0] || {}, ob = c.opt('b'), cashSet = ob === 'cash' || (ob !== 'accrual' && /PAYMENT|CASH/i.test(org.SalesTaxBasis || ''));
    var TR = {}; ((c.data.tax_rates || {}).TaxRates || []).forEach(function (t) { TR[t.TaxType] = t; });
    var inP = function (d) { return d && d >= from && d <= to; }, lines = [], docTaxBad = 0, docGrossBad = 0, unknown = {}, docs = 0;
    var add = function (doc, side, sign, src, dd) {
      if (!inP(dd)) return; docs++;
      var lt = 0, lg = 0, incl = (doc.LineAmountTypes || 'Exclusive') === 'Inclusive', f = doc.CurrencyCode && doc.CurrencyCode !== c.currency ? (XK.num(doc.CurrencyRate) || 1) : 1;
      (doc.LineItems || []).forEach(function (l) {
        var tt = l.TaxType || 'NONE', t = TR[tt], tax = XK.num(l.TaxAmount) || 0, amt = XK.num(l.LineAmount) || 0, net = incl ? amt - tax : amt; lt += tax; lg += net + tax;
        if (!t && tt !== 'NONE') unknown[tt] = 1;
        var n2 = r2(sign * net / f), g = r2(sign * tax / f);
        lines.push({ date: dd, month: dd.slice(0, 7), src: src, ref: doc.InvoiceNumber || doc.CreditNoteNumber || doc.Reference || '', contact: (doc.Contact || {}).Name || '', acct: l.AccountCode || '', tt: tt, rate: t ? t.Name : tt, pct: t ? XK.num(t.EffectiveRate) : null, side: side, net: n2, gst: g, gross: r2(n2 + g) });
      });
      if (!XK.near(r2(lt), XK.num(doc.TotalTax) || 0)) docTaxBad++;
      if (!XK.near(r2(lg), XK.num(doc.Total) || 0)) docGrossBad++;
    };
    var fin = c.fan('paid_inv'), byId = {}, cashDone = cashSet && fin != null && fin.every(function (x) { return !x.error; }), nPay = 0;
    if (fin) fin.forEach(function (x) { ((x.value || {}).Invoices || []).forEach(function (d) { byId[d.InvoiceID] = d; }); });
    if (cashDone) c.rows('payments').forEach(function (p) { var d = byId[(p.Invoice || {}).InvoiceID], tot = d ? XK.num(d.Total) : 0, k = tot ? (XK.num(p.Amount) || 0) / tot : 0; if (!d || !k || p.Status === 'DELETED') return; nPay++; var sc = function (v) { return (XK.num(v) || 0) * k; };
      add(Object.assign({}, d, { TotalTax: sc(d.TotalTax), Total: sc(d.Total), LineItems: (d.LineItems || []).map(function (l) { return Object.assign({}, l, { LineAmount: sc(l.LineAmount), TaxAmount: sc(l.TaxAmount) }); }) }), d.Type === 'ACCREC' ? 'sales' : 'purchases', 1, d.Type === 'ACCREC' ? 'Invoice payment' : 'Bill payment', XK.isoDate(p.Date)); });
    else c.rows('invoices').forEach(function (d) { if (d.Status === 'AUTHORISED' || d.Status === 'PAID') add(d, d.Type === 'ACCREC' ? 'sales' : 'purchases', 1, d.Type === 'ACCREC' ? 'Invoice' : 'Bill', XK.isoDate(d.DateString || d.Date)); });
    c.rows('credit_notes').forEach(function (d) { if (/^(AUTHORISED|PAID)$/.test(d.Status || '')) add(d, d.Type === 'ACCRECCREDIT' ? 'sales' : 'purchases', -1, d.Type === 'ACCRECCREDIT' ? 'Sales credit note' : 'Bill credit note', XK.isoDate(d.DateString || d.Date)); });
    var gstRow = function (v) { var w = v ? XK.walk(v) : null, l = w ? w.lines.filter(function (x) { return x.kind === 'row' && /^gst$|^gst (payable|liability)|^bas liabilit/i.test(x.label); })[0] : null; return l ? { v: l.values[0], id: l.id, label: l.label } : null; };
    var g1 = gstRow(c.data.bs_end), g0 = gstRow(c.data.bs_start), accts = (c.data.accounts || {}).Accounts || [], acc = accts.filter(function (a) { return g1 && a.AccountID === g1.id; })[0] || accts.filter(function (a) { return a.SystemAccount === 'GST'; })[0], code = acc ? acc.Code : null, settled = 0, settledN = 0;
    c.rows('bank_tx').forEach(function (d) {
      if (d.Status !== 'AUTHORISED' || !(d.Type === 'RECEIVE' || d.Type === 'SPEND')) return; var dd = XK.isoDate(d.DateString || d.Date); if (!inP(dd)) return;
      if (code && (d.LineItems || []).some(function (l) { return l.AccountCode === code; })) { (d.LineItems || []).forEach(function (l) { if (l.AccountCode === code) { settled = r2(settled + (d.Type === 'SPEND' ? 1 : -1) * (XK.num(l.LineAmount) || 0)); settledN++; } }); }
      else add(d, d.Type === 'RECEIVE' ? 'sales' : 'purchases', 1, d.Type === 'RECEIVE' ? 'Receive money' : 'Spend money', dd);
    });
    // ---- grid: rows = side × tax type, columns = months of the period + Total
    var n = (+to.slice(0, 4) - +from.slice(0, 4)) * 12 + (+to.slice(5, 7) - +from.slice(5, 7)) + 1, months = XK.monthsEnding(to, Math.max(1, n)).map(function (m) { return m.key; });
    var R = {}, T = { out: 0, inn: 0 }, M = {}; months.forEach(function (k) { M[k] = { out: 0, inn: 0 }; });
    lines.forEach(function (l) { var key = l.side + '|' + l.tt, x = R[key] || (R[key] = { side: l.side, tt: l.tt, rate: l.rate, pct: l.pct, gst: {}, net: {}, tg: 0, tn: 0 }); x.gst[l.month] = r2((x.gst[l.month] || 0) + l.gst); x.net[l.month] = r2((x.net[l.month] || 0) + l.net); x.tg = r2(x.tg + l.gst); x.tn = r2(x.tn + l.net);
      var s = l.side === 'sales' ? 'out' : 'inn'; T[s] = r2(T[s] + l.gst); if (M[l.month]) M[l.month][s] = r2(M[l.month][s] + l.gst); });
    var rows = Object.keys(R).map(function (k) { return R[k]; }).filter(function (x) { return x.tg || x.tn; }).sort(function (a, b) { return (a.side === b.side ? 0 : a.side === 'sales' ? -1 : 1) || Math.abs(b.tg) - Math.abs(a.tg) || a.rate.localeCompare(b.rate); });
    var net = r2(T.out - T.inn), view = c.view === 'net' ? 'net' : 'gst', ttf = self._tt && rows.some(function (x) { return x.tt === self._tt; }) ? self._tt : '';
    var shown = rows.filter(function (x) { return !ttf || x.tt === ttf; }), cellRow = function (x) { var o = { side: x.side === 'sales' ? 'GST collected' : 'GST paid', rate: x.rate, code: x.tt, pctS: x.pct == null ? '' : x.pct + '%', total: view === 'net' ? x.tn : x.tg }; months.forEach(function (k) { o['m' + k] = (view === 'net' ? x.net : x.gst)[k] || 0; }); return o; };
    var footRow = function (label, side, sg) { var o = { side: label, total: 0 }; months.forEach(function (k) { o['m' + k] = r2(XK.sum(shown.filter(function (x) { return !side || x.side === side; }).map(function (x) { return (x.side === 'sales' || !sg ? 1 : -1) * ((view === 'net' ? x.net : x.gst)[k] || 0); }))); }); o.total = r2(XK.sum(shown.filter(function (x) { return !side || x.side === side; }).map(function (x) { return (x.side === 'sales' || !sg ? 1 : -1) * (view === 'net' ? x.tn : x.tg); }))); return o; };
    var open = g0 ? g0.v : null, close = g1 ? g1.v : null, expected = open == null ? null : r2(open + net - settled), diff = expected == null || close == null ? null : r2(close - expected);
    body.innerHTML = '<div class="xk-banner na" style="margin-bottom:12px"><strong>BAS preparation review, not a lodgeable BAS</strong> — GST by tax type calculated from your Xero transactions on the <strong>' + (cashSet ? 'cash (payments)' : 'accrual (invoice)') + '</strong> basis' + (cashSet && !cashDone ? ' — ' + (fin == null ? 'loading the paid invoices…' : 'some paid invoices could not be loaded, so these figures are on the invoice basis') : '') + '. Not tax advice.</div>' +
      XK.kpis([{ label: 'GST collected', value: T.out }, { label: 'GST paid', value: T.inn }, { label: 'Net GST ' + (net >= 0 ? 'payable' : 'refundable'), value: net }, { label: 'Difference to the GST account', value: diff, text: diff == null ? 'N/A' : null, red: diff != null && !cashSet && !XK.near(diff, 0) }], c) +
      '<div class="xk-card" style="margin-top:16px"><h3>' + (view === 'net' ? 'Net amounts' : 'GST amounts') + ' by tax type and month</h3><label class="muted">Tax type <select id="tt-filter"><option value="">All tax types</option>' + rows.map(function (x) { return x.tt; }).filter(function (v, i, a) { return a.indexOf(v) === i; }).map(function (t) { return '<option value="' + XK.h(t) + '"' + (t === ttf ? ' selected' : '') + '>' + XK.h((TR[t] || {}).Name || t) + '</option>'; }).join('') + '</select></label><div id="tt-grid"></div></div>' +
      '<div class="xk-card" style="margin-top:16px"><h3>GST collected vs GST paid by month</h3><div id="tt-bars"></div></div>' +
      '<div class="xk-card" style="margin-top:16px"><h3>Reconciliation to the GST account' + (g1 ? ' (' + XK.h(g1.label) + (code ? ', ' + XK.h(code) : '') + ')' : '') + '</h3><table class="xk-grid"><tbody>' +
      [['GST account balance at ' + XK.shortDate(c.inputs.prev_end), open], ['+ GST collected', T.out], ['− GST paid', -T.inn], ['− Paid to / + refunded by the ATO in the period (' + settledN + ' line' + (settledN === 1 ? '' : 's') + ')', -settled], ['= Expected balance at ' + XK.shortDate(to), expected], ['GST account balance at ' + XK.shortDate(to) + ' (Balance Sheet)', close], ['Difference', diff]].map(function (r, i) { return '<tr' + (i >= 4 ? ' class="k-total"' : '') + '><td>' + XK.h(r[0]) + '</td><td class="num">' + (r[1] == null ? 'N/A — not in source' : money(r[1])) + '</td></tr>'; }).join('') + '</tbody></table>' +
      (diff != null && !XK.near(diff, 0) ? '<p class="muted">Why it can differ (not checked): GST in manual journals, payments to the ATO not coded to the GST account, documents approved after the period' + (cashSet ? ', and on the cash basis the GST account moves on invoices, not payments' : '') + '.</p>' : '') + '</div>';
    XK.grid(document.getElementById('tt-grid'), { rows: shown.map(cellRow), columns: [{ key: 'side', title: '' }, { key: 'rate', title: 'Tax type' }, { key: 'code', title: 'Code' }, { key: 'pctS', title: 'Rate', num: true }].concat(months.map(function (k) { return { key: 'm' + k, title: XK.monthLabel(k), money: true }; })).concat([{ key: 'total', title: 'Total', money: true }]),
      foot: [footRow('Total GST collected', 'sales'), footRow('Total GST paid', 'purchases'), footRow(view === 'net' ? 'Net (sales − purchases)' : 'Net GST (collected − paid)', null, true)], empty: 'No GST in this period.' }, c);
    var fl = document.getElementById('tt-filter'); if (fl) fl.addEventListener('change', function () { self._tt = this.value; c.change({}, {}); });
    XK.bars(document.getElementById('tt-bars'), { title: 'GST collected vs GST paid', labels: months.map(XK.monthLabel), series: [{ name: 'GST collected', values: months.map(function (k) { return M[k].out; }) }, { name: 'GST paid', values: months.map(function (k) { return M[k].inn; }) }] }, c);
    // ---- checks
    var monthBad = rows.filter(function (x) { return !XK.near(XK.sum(months.map(function (k) { return x.gst[k] || 0; })), x.tg) || !XK.near(XK.sum(months.map(function (k) { return x.net[k] || 0; })), x.tn); });
    var lineSum = { out: XK.sum(lines.filter(function (l) { return l.side === 'sales'; }).map(function (l) { return l.gst; })), inn: XK.sum(lines.filter(function (l) { return l.side !== 'sales'; }).map(function (l) { return l.gst; })) }, typeSum = { out: XK.sum(rows.filter(function (x) { return x.side === 'sales'; }).map(function (x) { return x.tg; })), inn: XK.sum(rows.filter(function (x) { return x.side !== 'sales'; }).map(function (x) { return x.tg; })) };
    var trunc = ['invoices', 'credit_notes', 'bank_tx', 'payments'].filter(function (id) { return c.truncated(id) || (id === 'payments' && cashSet && c.errors.payments); });
    var checks = [
      { name: 'Σ months = the period total for every tax type (GST and net)', pass: monthBad.length === 0, detail: monthBad.length ? 'Differs: ' + monthBad.map(function (x) { return x.rate; }).join(', ') : rows.length + ' tax type row(s) × ' + months.length + ' month(s)' },
      { name: 'Tax types add up to the tax lines; net GST = GST collected − GST paid', pass: XK.near(typeSum.out, lineSum.out) && XK.near(typeSum.inn, lineSum.inn) && XK.near(net, r2(T.out - T.inn)) && XK.near(T.out, typeSum.out), detail: money(T.out) + ' − ' + money(T.inn) + ' = ' + money(net) },
      { name: 'Each document\'s lines add up to its total tax and its total (Xero\'s TotalTax and Total)', pass: docTaxBad === 0 && docGrossBad === 0, detail: docTaxBad + docGrossBad ? docTaxBad + ' differ on tax, ' + docGrossBad + ' on the total' : docs + ' document(s)' },
      { name: 'Every tax type used is one of the organisation\'s tax rates', pass: Object.keys(unknown).length === 0, detail: Object.keys(unknown).length ? 'Unknown: ' + Object.keys(unknown).join(', ') : rows.length + ' row(s)' },
      diff == null ? { name: 'Net GST = the GST account movement on the Balance Sheet (end − start) − GST paid to the ATO', pass: null, detail: c.err('bs_end') || c.err('bs_start') || 'N/A — no GST line on the Balance Sheet' }
        : cashSet ? { name: 'GST account movement vs net GST (information — on the cash basis the GST account moves on invoices)', pass: null, info: true, detail: 'Difference ' + money(diff) }
        : { name: 'Net GST = the GST account movement on the Balance Sheet (end − start) − GST paid to the ATO', pass: XK.near(diff, 0), detail: money(r2(close - open)) + ' movement = ' + money(net) + ' − ' + money(settled) + ' paid' + (XK.near(diff, 0) ? '' : ' — difference ' + money(diff) + ' (see the reconciliation)') },
      { name: 'All documents in the period loaded', pass: !trunc.length, detail: trunc.length ? 'May be truncated (over 20 pages): ' + trunc.join(', ') : docs + ' document(s)' }
    ];
    if (cashSet) checks.push({ name: 'Cash basis: every payment\'s invoice loaded', pass: fin == null ? null : cashDone && nPay === c.rows('payments').filter(function (p) { return p.Status !== 'DELETED' && (p.Invoice || {}).InvoiceID; }).length, detail: fin == null ? (c.live ? 'Loading' : 'Needs the live report') : nPay + ' of ' + c.rows('payments').length + ' payment(s)' });
    this._x = { rows: rows, months: months, T: T, net: net, cash: cashSet, recon: [['Opening GST balance', open], ['GST collected', T.out], ['GST paid', -T.inn], ['Paid to / refunded by the ATO', -settled], ['Expected closing balance', expected], ['Closing GST balance (Balance Sheet)', close], ['Difference', diff]] };
    return { checks: checks, period: XK.periodLine(from, to) + ' · ' + (cashSet ? 'Cash' : 'Accrual') + ' GST basis',
      notes: ['GST rebuilt from the tax lines of invoices, bills, credit notes and spend / receive money ' + (cashSet ? 'paid in the period (each payment\'s share of its invoice; credit notes and spend / receive money by their date)' : 'dated in the period') + ', grouped by Xero tax rate. Payments to or refunds from the ATO (lines coded to the GST account) reconcile the account instead.', 'Manual journals with GST are not included (they appear as a difference to the GST account).'],
      na: ['A lodgeable BAS and its lodgement status (no activity-statement endpoint in the Xero API)'] };
  },
  excel: function (c) {
    var x = this._x; if (!x) return [];
    var head = function (name) { return [[{ v: c.company || 'N/A — not in source', s: 'title' }], [{ v: name, s: 'bold' }], [XK.periodLine(c.inputs.from_date, c.inputs.to_date) + ' · ' + (x.cash ? 'Cash' : 'Accrual') + ' GST basis'], []]; }, mv = function (v) { return v == null ? 'N/A' : { v: v, s: 'money' }; };
    var sheet = function (name, key, tk) { var hd = ['', 'Tax type', 'Code', 'Rate'].concat(x.months.map(XK.monthLabel), ['Total']).map(function (t) { return { v: t, s: 'bold' }; }), tot = function (side) { return x.months.map(function (k) { return mv(XK.sum(x.rows.filter(function (r) { return r.side === side; }).map(function (r) { return r[key][k] || 0; }))); }).concat([mv(XK.sum(x.rows.filter(function (r) { return r.side === side; }).map(function (r) { return r[tk]; })))]); };
      return head(name).concat([hd]).concat(x.rows.map(function (r) { return [r.side === 'sales' ? 'GST collected' : 'GST paid', r.rate, r.tt, r.pct == null ? '' : r.pct + '%'].concat(x.months.map(function (k) { return mv(r[key][k] || 0); }), [mv(r[tk])]); }))
        .concat([[{ v: 'Total sales', s: 'bold' }, '', '', ''].concat(tot('sales')), [{ v: 'Total purchases', s: 'bold' }, '', '', ''].concat(tot('purchases'))]); };
    return [{ name: 'GST by tax type', rows: sheet('GST by tax type and month', 'gst', 'tg'), widths: [16, 26, 14, 8].concat(x.months.map(function () { return 14; }), [16]) }, { name: 'Net by tax type', rows: sheet('Net amounts by tax type and month', 'net', 'tn'), widths: [16, 26, 14, 8].concat(x.months.map(function () { return 14; }), [16]) },
      { name: 'GST reconciliation', rows: head('Reconciliation to the GST account').concat([[{ v: 'Line', s: 'bold' }, { v: 'Amount', s: 'bold' }]]).concat(x.recon.map(function (r) { return [r[0], mv(r[1])]; })), widths: [44, 18] }];
  }
});
