XK.app({
  title: 'All reports', primary: 'org', org: 'org', conns: 'connections', noBasis: true, noHead: false,
  inputs: { org: 'org', display: 'display' },
  defaults: { org: '', display: '{"cents":1,"k":0,"zeros":1,"neg":"paren","red":1,"hdr":1,"ftr":1,"style":"xero","dens":"100","p":"custom","a":"custom","c":"none","v":"","o":"q="}' },
  uses: { org: ['org'], connections: [] },
  tools: { org: 'get_organisation', connections: 'list_connections' },
  render: function (c) {
    var body = c.body, q = String(c.opt('q') || '').toLowerCase();
    // Xero's report catalogue (Reporting → All reports) with this agent's coverage. live = a tested report skill in this agent.
    // live = a tested kit report; spec = the agent builds it from a written specification (results can vary); part = partly covered.
    var L = 'live', W = 'spec', P = 'part', N = 'none';
    // [name, status, prompt id ('' = an added skill), what to ask, skill]
    var CAT = [
      ['Financial statements', [['Balance Sheet', L, 'P07', 'Balance sheet as at today', 'xero-balance-sheet'], ['Blank Report', N], ['Budget Variance', L, '', 'Budget vs actual this financial year', 'xero-budget-vs-actual'], ['Depreciation Schedule', N], ['Disposal Schedule', N], ['Fixed Asset Reconciliation', N], ['Management Report', N], ['Movements in Equity', N], ['Profit and Loss', L, 'P06', 'Profit and loss this financial year to date', 'xero-profit-and-loss'], ['Profit and Loss by tracking category', L, '', 'Profit and loss by region for last quarter', 'xero-tracking-category-pnl'], ['Statement of Cash Flows – Direct Method', N], ['Tax Depreciation Schedule', N], ['Tax Disposal Schedule', N]]],
      ['Payables and receivables', [['Aged Payables Detail', P, 'P09', 'Aged payables — click a supplier for its bills', 'xero-aged-payables'], ['Aged Payables Summary', L, 'P09', 'Aged payables at the end of this month', 'xero-aged-payables'], ['Aged Receivables Detail', P, 'P08', 'Aged receivables — click a customer for its invoices', 'xero-aged-receivables'], ['Aged Receivables Summary', L, 'P08', 'Aged receivables at the end of this month', 'xero-aged-receivables'], ['Expense Claim Detail', N], ['Income and Expenses by Contact', N], ['Payable Invoice Detail', N], ['Payable Invoice Summary', N], ['Receivable Invoice Detail (sales register)', L, '', 'Sales register for September', 'xero-sales-register'], ['Receivable Invoice Summary', N], ['Customer Invoice Activity', N], ['Supplier Bill Activity', N]]],
      ['Reconciliations', [['Account Summary', N], ['Account Transactions', N], ['Bank Reconciliation', L, '', 'Bank reconciliation status', 'xero-bank-reconciliation-status'], ['Bank Summary', P, 'P10', 'Cash summary this financial year (opening and closing bank balances)', 'xero-cash-summary'], ['Duplicate Statement Lines', N]]],
      ['Taxes and balances', [['Activity Statement', P, 'P05', 'GST summary for last quarter (not the lodged BAS)', 'xero-activity-statement'], ['GST Reconciliation', L, '', 'GST reconciliation detail for last quarter', 'xero-gst-reconciliation-detail'], ['Journal Report', N], ['General Ledger', L, '', 'General ledger for September (may be unavailable: needs the journals scope)', 'xero-general-ledger'], ['Trial Balance', L, '', 'Trial balance as at today', 'xero-trial-balance'], ['Taxable Payments Annual Report', N]]],
      ['Dashboards and analytics', [['Business overview', L, 'P01', 'Business overview', 'xero-business-overview'], ['Sales overview', L, 'P02', 'Sales overview', 'xero-sales-overview'], ['Purchases overview', L, 'P03', 'Purchases overview', 'xero-purchases-overview'], ['Cash Summary', L, 'P10', 'Cash summary this financial year to date', 'xero-cash-summary'], ['Performance overview', L, 'P11', 'Performance overview for the 12 months to last month', 'xero-performance-overview'], ['Cash position', L, 'P12', 'Cash position', 'xero-cash-position'], ['Cash flow manager', L, 'P13', 'Cash flow for the next 30 days', 'xero-cash-flow-manager'], ['Business health scorecard', L, 'P14', 'Business health scorecard for last month', 'xero-business-health-scorecard'], ['Visualise', L, 'P15', 'Visualise my income and expenses', 'xero-visualise']]],
      ['Bookkeeping workflows and packs', [['Month-end task list', L, '', 'Month-end task list for September', 'xero-month-end-task-list'], ['Exceptions dashboard', L, '', 'Exceptions dashboard', 'xero-exceptions-dashboard'], ['Report pack', L, '', 'Month-end report pack', 'xero-report-pack'], ['All reports (this page)', L, 'P04', 'What reports can you do?', 'xero-reports-catalog']]]];
    var DEF = ['Activity Statement', 'Aged Payables Summary', 'Aged Receivables Summary', 'Balance Sheet', 'Cash Summary', 'Performance overview', 'Profit and Loss'];
    var all0 = [].concat.apply([], CAT.map(function (g) { return g[1]; })), favO = c.opt('fav');
    var FAV = favO == null || favO === '' ? DEF : favO === '-' ? [] : String(favO).split(',').map(function (i) { return (all0[+i] || [])[0]; }).filter(Boolean);
    var chip = { live: '<span class="xk-chip on">Live</span>', spec: '<span class="xk-chip">Built on request</span>', part: '<span class="xk-chip">Partly</span>', none: '<span class="xk-chip">No prompt yet</span>' };
    var star = function (r) { var on = FAV.indexOf(r[0]) >= 0; return '<button type="button" class="rc-star no-print" data-i="' + all0.indexOf(r) + '" title="' + (on ? 'Remove from favourites' : 'Add to favourites') + '" aria-pressed="' + on + '" style="background:none;border:0;cursor:pointer;color:var(--accent);font-size:15px;padding:0 4px 0 0">' + (on ? '★' : '☆') + '</button>'; };
    var card = function (r) { return '<div class="xk-kpi" style="margin-bottom:8px"><div class="lbl">' + star(r) + XK.h(r[0]) + ' ' + chip[r[1]] + (r[2] ? ' <span class="muted">' + r[2] + '</span>' : r[1] !== N ? ' <span class="muted">Added</span>' : '') + '</div>' + (r[3] ? '<div class="sub">Ask: "' + XK.h(r[3]) + '"</div>' : '<div class="sub muted">Not in this agent yet — open it in Xero → Reporting</div>') + '</div>'; };
    var match = function (r) { return !q || r[0].toLowerCase().indexOf(q) >= 0; }, all = [].concat.apply([], CAT.map(function (g) { return g[1]; }));
    var favRows = all.filter(function (r) { return FAV.indexOf(r[0]) >= 0 && match(r); });
    body.innerHTML = '<div class="xk-card"><label>Search reports <input type="search" id="rc-q" value="' + XK.h(q) + '" placeholder="e.g. aged"></label> <span class="muted">' + all.filter(function (r) { return r[1] === L; }).length + ' live · ' + all.filter(function (r) { return r[1] === W; }).length + ' built on request · ' + all.filter(function (r) { return r[1] === P; }).length + ' partly · ' + all.filter(function (r) { return r[1] === N; }).length + ' not yet</span></div>' +
      (favRows.length ? '<div class="xk-card"><h3>Favourites</h3><p class="muted no-print">Click ☆ on any report to add it here (★ removes it). Your favourites are saved with this report.</p><div class="xk-grid3">' + favRows.map(card).join('') + '</div></div>' : '') +
      CAT.map(function (g) { var rows = g[1].filter(match); return rows.length ? '<div class="xk-card"><h3>' + XK.h(g[0]) + '</h3><div class="xk-grid3">' + rows.map(card).join('') + '</div></div>' : ''; }).join('') +
      '<p class="muted">Name a report and confirm the organisation and period, and it is generated live from Xero. Custom saved reports exist per organisation in Xero and are not available through the Xero API.</p>';
    var inp = document.getElementById('rc-q'); if (inp) inp.addEventListener('change', function () { c.setOpt('q', this.value.replace(/[;=]/g, ' ')); });
    body.querySelectorAll('.rc-star').forEach(function (b) { b.addEventListener('click', function () { var nm = (all0[+b.getAttribute('data-i')] || [])[0], cur = FAV.slice(), k = cur.indexOf(nm); if (k >= 0) cur.splice(k, 1); else cur.push(nm); var ids = cur.map(function (n) { return all0.findIndex(function (r) { return r[0] === n; }); }).filter(function (i) { return i >= 0; }); ids = ids.slice(-20); c.setOpt('fav', ids.length ? ids.join(',') : '-'); }); });
    var STAT = { live: 'Live', spec: 'Built on request', part: 'Partly', none: 'No prompt yet' };
    this._x = { rows: [].concat.apply([], CAT.map(function (g) { return g[1].map(function (r) { return [g[0], r[0], STAT[r[1]], r[2] || (r[1] !== N ? 'Added' : ''), r[3] || 'Open it in Xero → Reporting', FAV.indexOf(r[0]) >= 0 ? 'Yes' : '']; }); })) };
    var mapped = all.every(function (r) { return r[1] === N || /^P\d\d$/.test(r[2] || '') || /^xero-/.test(r[4] || ''); }), listed = all.map(function (r) { return r[4]; });
    var SKILLS = ['xero-activity-statement', 'xero-aged-payables', 'xero-aged-receivables', 'xero-balance-sheet', 'xero-bank-reconciliation-status', 'xero-budget-vs-actual', 'xero-business-health-scorecard', 'xero-business-overview', 'xero-cash-flow-manager', 'xero-cash-position', 'xero-cash-summary', 'xero-exceptions-dashboard', 'xero-general-ledger', 'xero-gst-reconciliation-detail', 'xero-month-end-task-list', 'xero-performance-overview', 'xero-profit-and-loss', 'xero-purchases-overview', 'xero-report-pack', 'xero-reports-catalog', 'xero-sales-overview', 'xero-sales-register', 'xero-tracking-category-pnl', 'xero-trial-balance', 'xero-visualise'];
    var missing = SKILLS.filter(function (k) { return listed.indexOf(k) < 0; });
    return { checks: [
      { name: 'Every listed report maps to a Prompt ID, an added skill, or is flagged "no prompt yet"', pass: mapped, detail: all.length + ' reports' },
      { name: 'Every report skill in this agent is listed', pass: missing.length === 0, detail: missing.join(', ') || SKILLS.length + ' skills' }], notes: [JSON.stringify(CAT).indexOf('"spec"') >= 0 ? '"Built on request" reports are written by the agent from a specification each time, so their layout can vary; "Live" reports are tested kit reports.' : '"Live" reports are tested kit reports: the same tested document every time, checked against Xero on every open.'], na: ['Custom saved reports and Xero\'s own favourites (not in the Xero API — favourites here are the ones you star)'], period: 'Xero → Reporting → All reports' };
  },
  excel: function (c) {
    var x = this._x; if (!x) return [];
    var rows = [[{ v: c.company || 'N/A — not in source', s: 'title' }], [{ v: 'All reports', s: 'bold' }], ['Xero → Reporting → All reports'], [], ['Group', 'Report', 'Status', 'Prompt ID', 'What to ask', 'Favourite'].map(function (t) { return { v: t, s: 'bold' }; })].concat(x.rows);
    return [{ name: 'All reports', rows: rows, widths: [30, 34, 18, 12, 64, 10] }];
  }
});
