XK.app({
  title: 'Visualise', primary: 'pnl_12', dated: ['bs_12'], org: 'org', conns: 'connections',
  inputs: { asAt: 'end_date', basis: 'basis', org: 'org', display: 'display' },
  defaults: { end_date: '2026-08-31', m_start: '2026-08-01', window_start: '2025-09-01', ext: '{}', bench: '{}', basis: 'Accrual', org: '',
    display: '{"cents":0,"k":0,"zeros":0,"neg":"paren","red":1,"hdr":1,"ftr":1,"style":"xero","dens":"100","p":"custom","a":"end_last_month","c":"none","v":"profitability","o":""}' },
  uses: { pnl_12: ['m_start', 'end_date', 'org'], pnl_12_cash: ['m_start', 'end_date', 'org'], bs_12: ['end_date', 'org'], bank: ['m_start', 'end_date', 'org'], transfers: ['org'], pnl_total: ['window_start', 'end_date', 'org'], pnl_total_cash: ['window_start', 'end_date', 'org'], org: ['org'], connections: [] },
  fan: { bank: function (inp, c) { return c.view === 'cash' ? XK.monthsEnding(inp.end_date, 12).map(function (m) { return { key: m.key, inputs: { m_start: m.start, end_date: m.end < inp.end_date ? m.end : inp.end_date } }; }) : []; } },
  tools: { pnl_12: 'get_profit_and_loss (12 monthly columns)', pnl_12_cash: 'get_profit_and_loss (12 monthly columns, cash basis)', bs_12: 'get_balance_sheet (12 month-ends)', bank: 'get_bank_summary (per month, Cash tab)', transfers: 'list_bank_transfers (between your accounts — taken out of Cash)', pnl_total: 'get_profit_and_loss (the 12 months as one — tie)', pnl_total_cash: 'get_profit_and_loss (the 12 months as one — tie, cash basis)', org: 'get_organisation', connections: 'list_connections' },
  asats: [['end_last_month', 'End of last month'], ['end_this_month', 'End of this month'], ['end_last_fy', 'End of last financial year'], ['custom', 'Custom']],
  views: [['profitability', 'Profitability'], ['cash', 'Cash'], ['accounts', 'Accounts'], ['external', 'External data'], ['kpis', 'KPIs'], ['benchmarks', 'Industry benchmarks']],
  derive: function (inp) { var p = inp.end_date.split('-'), d = new Date(Date.UTC(+p[0], +p[1] - 12, 1)); return { m_start: inp.end_date.slice(0, 8) + '01', window_start: d.toISOString().slice(0, 10) }; },
  render: function (c) {
    var Bk = c.inputs.basis === 'Cash' ? '_cash' : '', PL = { pnl_12: 1, pnl_total: 1 }, D = function (id) { return c.data[PL[id] ? id + Bk : id]; }, Er = function (id) { return c.errors[PL[id] ? id + Bk : id]; }, Em = function (id) { return c.err(PL[id] ? id + Bk : id); };
    var self = this, body = c.body, d0 = Object.assign({}, c.display, { cents: 0 }), money = function (v) { return XK.money(v, c.currency, d0); };
    if (Er('pnl_12')) { body.innerHTML = '<p class="xk-err">' + XK.h(Em('pnl_12')) + '</p>'; return { checks: [{ name: 'Monthly Profit and Loss loaded', pass: false, detail: Em('pnl_12') }] }; }
    if (!D('pnl_12')) return {};
    var end = c.inputs.end_date, keys = XK.monthsEnding(end, 12).map(function (m) { return m.key; }), labs = keys.map(function (k) { return XK.monthLabel(k).slice(0, 3); }), ending = ' · Monthly ending ' + XK.asOfLine(end).replace(/^As at /, '');
    var w = XK.walk(D('pnl_12')), mc = XK.monthCols(w), bw = c.data.bs_12 ? XK.walk(c.data.bs_12) : null, bmc = bw ? XK.monthCols(bw) : null;
    var P = keys.map(function (k) { var i = mc && mc.idx[k]; return i == null ? null : XK.plParts(w, i); }), B = keys.map(function (k) { var i = bmc && bmc.idx[k]; return i == null ? null : XK.bsParts(bw, i); });
    var ser = function (f) { return P.map(function (p) { return p ? f(p) : null; }); }, bser = function (f) { return B.map(function (b, i) { return b && P[i] ? f(b, P[i], +XK.monthsEnding(end, 12)[i].end.slice(8)) : null; }); };
    var view = c.view || 'profitability', opt = function (id, def) { return c.opt(id) || def; }, pick = function (id, list, cur) { return '<select id="vz-' + id + '">' + list.map(function (o) { return '<option value="' + XK.h(o[0]) + '"' + (o[0] === cur ? ' selected' : '') + '>' + XK.h(o[1]) + '</option>'; }).join('') + '</select>'; };
    var tabs = '<div class="xk-tabs">' + (this.views || []).map(function (v) { return '<button type="button" class="xk-tab' + (v[0] === view ? ' on' : '') + '" data-v="' + v[0] + '">' + v[1] + '</button>'; }).join('') + '</div>';
    var html = '', after = [], extraChecks = [], chips = null, insight = {};
    var gp = function (p) { return p.gp != null ? p.gp : p.trading - p.cos; }, div = function (a, b) { return a == null || !b ? null : a / b; };
    if (view === 'profitability') {
      var G = [['ie', 'Income vs Expenses'], ['trading', 'Sales'], ['cos', 'Cost of sales'], ['otherIncome', 'Other income'], ['opex', 'Operating expenses'], ['gp', 'Gross profit'], ['np', 'Net profit']], g = opt('g', 'ie'), gl = G.filter(function (x) { return x[0] === g; })[0] || G[0];
      var series = g === 'ie' ? [{ name: 'Income', values: ser(function (p) { return p.income; }), color: 'var(--c1)' }, { name: 'Expenses', values: ser(function (p) { return p.expenses; }), color: 'var(--c3)' }] : [{ name: gl[1], values: ser(function (p) { return g === 'gp' ? gp(p) : p[g]; }) }];
      html = '<div class="xk-card"><h3>' + XK.h(gl[1] + ending) + '</h3><p class="muted">Explore income, expenses, sales, cost of sales, other income and expenses. Graph: ' + pick('g', G, g) + '</p><div id="vz-ch"></div></div>';
      after.push(function () { XK.bars(document.getElementById('vz-ch'), { title: gl[1], labels: labs, series: series }, c); });
      var inc = ser(function (p) { return p.income; }), ex = ser(function (p) { return p.expenses; }), np = ser(function (p) { return p.np; }), first = function (a) { return a.filter(function (v) { return v != null; })[0]; }, lastv = function (a) { return a.filter(function (v) { return v != null; }).slice(-1)[0]; };
      chips = [['trends', 'Explain the trends in my income and expenses'], ['perf', 'How is my business performing'], ['improve', 'How can I improve profit']];
      insight = { trends: 'Income went from ' + money(first(inc)) + ' in ' + labs[0] + ' to ' + money(lastv(inc)) + ' in ' + labs[11] + '; expenses from ' + money(first(ex)) + ' to ' + money(lastv(ex)) + '.',
        perf: 'Over the 12 months net profit was ' + money(XK.sum(np.filter(function (v) { return v != null; }))) + ' on income of ' + money(XK.sum(inc.filter(function (v) { return v != null; }))) + ' (' + XK.pct(div(XK.sum(np.filter(function (v) { return v != null; })), XK.sum(inc.filter(function (v) { return v != null; })))) + ' net margin).',
        improve: (function () { var rows = w.lines.filter(function (l) { return l.kind === 'row' && XK.isDeduction(l.group); }).map(function (l) { return { label: l.label, v: XK.sum(l.values.filter(function (v) { return v != null; })) }; }).sort(function (a, b) { return b.v - a.v; }).slice(0, 3); return 'Your three largest costs over the 12 months: ' + rows.map(function (r) { return r.label + ' ' + money(r.v); }).join(', ') + '. Reducing any of these or lifting prices raises profit directly.'; })() };
    } else if (view === 'cash') {
      var fan = c.fan('bank'), acct = opt('acct', ''), rowsOf = function (v) { return XK.walk(v).lines.filter(function (l) { return l.kind === 'row'; }); };
      var accs = fan && fan[fan.length - 1] && fan[fan.length - 1].value ? rowsOf(fan[fan.length - 1].value).map(function (l) { return [l.label, l.label]; }) : [];
      var tr = c.errors.transfers ? null : ((c.data.transfers || {}).BankTransfers || []), tm = function (k, side) { return tr ? XK.sum(tr.filter(function (t) { var d = XK.isoDate(t.DateString || t.Date) || ''; return d.slice(0, 7) === k && (!acct || ((side === 'in' ? t.ToBankAccount : t.FromBankAccount) || {}).Name === acct); }).map(function (t) { return XK.num(t.Amount) || 0; })) : 0; };
      var mm = fan ? fan.map(function (it, i) { if (it.error || !it.value) return null; var rs = rowsOf(it.value).filter(function (l) { return !acct || l.label === acct; }), k = keys[i]; return { rin: Math.round((XK.sum(rs.map(function (l) { return l.values[1]; })) - tm(k, 'in')) * 100) / 100, rout: Math.round((XK.sum(rs.map(function (l) { return l.values[2]; })) - tm(k, 'out')) * 100) / 100 }; }) : null;
      html = '<div class="xk-card"><h3>Cash in vs Cash out' + ending + '</h3><p class="muted">Explore cash in, cash out and net cash flow (Xero\'s Bank Summary' + (tr ? ', excluding transfers between your own accounts' : '; transfers could not be loaded, so they are included') + '). Bank account: ' + pick('acct', [['', 'All accounts']].concat(accs), acct) + '</p>' + (fan == null ? '<p class="muted">' + (c.live ? 'Loading the 12 months…' : 'N/A in a snapshot — open the live report') + '</p>' : '<div id="vz-ch"></div>') + '</div>';
      if (mm) after.push(function () { XK.bars(document.getElementById('vz-ch'), { title: 'Cash in vs cash out', labels: labs, series: [{ name: 'Cash in', values: mm.map(function (m) { return m && m.rin; }), color: 'var(--pos)' }, { name: 'Cash out', values: mm.map(function (m) { return m && -m.rout; }), color: 'var(--neg)' }, { name: 'Net cash flow', values: mm.map(function (m) { return m && Math.round((m.rin - m.rout) * 100) / 100; }), color: 'var(--c3)' }] }, c); });
      extraChecks.push({ name: 'Transfers between your accounts loaded (taken out of cash in and out)', pass: c.errors.transfers ? false : c.data.transfers ? true : null, detail: c.errors.transfers ? c.err('transfers') : (tr || []).length + ' transfer(s)' });
      extraChecks.push({ name: 'Every month of the Bank Summary loaded', pass: fan == null ? null : fan.every(function (it) { return !it.error; }), detail: fan == null ? (c.live ? 'Loading' : 'N/A in a snapshot') : fan.filter(function (it) { return it.error; }).length + ' failed' });
    } else if (view === 'accounts') {
      var CT = [['line', 'Line'], ['column', 'Column'], ['stacked', 'Stacked'], ['bar', 'Bar'], ['area', 'Area'], ['doughnut', 'Doughnut']], ct = opt('ct', 'column'), bsSrc = opt('src', 'pl') === 'bs' && !!bw;
      var TOT = [['Total Trading Income', function (p) { return p.trading; }], ['Total Cost of Sales', function (p) { return p.cos; }], ['Gross Profit', gp], ['Total Other Income', function (p) { return p.otherIncome; }], ['Total Operating Expenses', function (p) { return p.opex; }]];
      if (bsSrc) TOT = [['Total Assets', 'totalAssets'], ['Total Liabilities', 'totalLiabilities'], ['Net Assets', 'netAssets'], ['Bank', 'bank']].map(function (t) { return [t[0], t[1]]; });
      var sw = bsSrc ? bw : w, smc = bsSrc ? bmc : mc, accRows = sw.lines.filter(function (l) { return l.kind === 'row'; }), sel = ['acc', 'acc2', 'acc3'].map(function (k) { return opt(k, ''); }).filter(Boolean);
      var picked = sel.map(function (lb) { var l = accRows.filter(function (x) { return x.label === lb; })[0]; return l ? { name: l.label, values: keys.map(function (k) { var i = smc && smc.idx[k]; return i == null ? null : l.values[i]; }) } : null; }).filter(Boolean);
      var accSeries = picked.length ? picked : TOT.map(function (t) { return { name: t[0], values: bsSrc ? B.map(function (x) { return x ? x[t[1]] : null; }) : ser(t[1]) }; });
      var tl = bsSrc ? 'Balance Sheet totals' : 'Profit and Loss totals', ao = accRows.map(function (l) { return [l.label, l.label]; });
      html = '<div class="xk-card"><h3>' + XK.h((picked.map(function (p) { return p.name; }).join(', ') || tl) + ending) + '</h3><p class="muted">View P&amp;L or Balance Sheet totals and accounts (up to three) and explore trends. Source: ' + pick('src', [['pl', 'Profit and Loss'], ['bs', 'Balance Sheet']], bsSrc ? 'bs' : 'pl') + ' Chart: ' + pick('ct', CT, ct) + ' Series: ' + pick('acc', [['', tl]].concat(ao), sel[0] || '') + (sel.length ? ' + ' + pick('acc2', [['', '—']].concat(ao), opt('acc2', '')) + ' + ' + pick('acc3', [['', '—']].concat(ao), opt('acc3', '')) : '') + '</p><div id="vz-ch"></div></div>';
      after.push(function () { var el = document.getElementById('vz-ch'), last = function (a) { return a.filter(function (v) { return v != null; }).slice(-1)[0]; };
        if (ct === 'doughnut') XK.donut(el, { title: 'Totals', items: accSeries.map(function (s) { return { label: s.name, value: bsSrc ? last(s.values) : XK.sum(s.values.filter(function (v) { return v != null; })) }; }) }, c);
        else if (ct === 'line' || ct === 'area') XK.line(el, { title: 'Accounts', labels: labs, series: accSeries, area: ct === 'area' }, c);
        else if (ct === 'bar') XK.hbars(el, { title: 'Accounts', labels: labs, series: accSeries }, c);
        else XK.bars(el, { title: 'Accounts', labels: labs, stacked: ct === 'stacked', series: accSeries }, c); });
    } else if (view === 'external') {
      var ext = {}; try { ext = JSON.parse(c.inputs.ext || '{}') || {}; } catch (e) { ext = {}; }
      var names = Object.keys(ext), en = opt('xs', names[0] || '');
      html = '<div class="xk-card"><h3>External data' + ending + '</h3><p class="muted">Custom metrics from outside Xero, shown beside your financials.</p>' + (names.length ? 'Metric: ' + pick('xs', names.map(function (n) { return [n, n]; }), en) + '<div id="vz-ch"></div><div id="vz-ch2"></div>' : '<p>N/A — no external data yet. Tell the agent your figures, e.g. "Staff employed: Jul 12, Aug 13", and it adds them to this report.</p>') + '</div>';
      if (names.length) after.push(function () { var s = ext[en] || {}; XK.line(document.getElementById('vz-ch'), { title: en, labels: labs, fmt: function (v) { return String(v); }, series: [{ name: en, values: keys.map(function (k) { return s[k] == null ? null : +s[k]; }) }] }, c);
        XK.bars(document.getElementById('vz-ch2'), { title: 'Income', labels: labs, series: [{ name: 'Total income', values: ser(function (p) { return p.income; }) }] }, c); });
    } else if (view === 'kpis' || view === 'benchmarks') {
      var K = [['dd', 'Debtors days', 'Accounts receivable ÷ total income × days in month', function (b, p, d) { return p.income ? b.ar / p.income * d : null; }, function (v) { return Math.round(v) + ' days'; }],
        ['cd', 'Creditors days', 'Accounts payable ÷ total expenses × days in month', function (b, p, d) { return p.expenses ? b.ap / p.expenses * d : null; }, function (v) { return Math.round(v) + ' days'; }],
        ['gpm', 'Gross profit margin', 'Gross profit ÷ trading income', function (b, p) { return div(gp(p), p.trading); }, function (v) { return (v * 100).toFixed(1) + '%'; }],
        ['npm', 'Net profit margin', 'Net profit ÷ total income', function (b, p) { return div(p.np, p.income); }, function (v) { return (v * 100).toFixed(1) + '%'; }],
        ['cr', 'Current ratio', 'Current assets ÷ current liabilities', function (b) { return div(b.currentAssets, b.currentLiabilities); }, function (v) { return v.toFixed(2); }],
        ['qr', 'Quick ratio', '(Bank + accounts receivable) ÷ current liabilities', function (b) { return div((b.bank || 0) + (b.ar || 0), b.currentLiabilities); }, function (v) { return v.toFixed(2); }],
        ['roa', 'Return on assets', 'Net profit for the month ÷ total assets', function (b, p) { return div(p.np, b.totalAssets); }, function (v) { return (v * 100).toFixed(2) + '%'; }],
        ['roe', 'Return on equity', 'Net profit for the month ÷ equity (net assets)', function (b, p) { return div(p.np, b.netAssets); }, function (v) { return (v * 100).toFixed(2) + '%'; }],
        ['debt', 'Debt ratio', 'Total liabilities ÷ total assets', function (b) { return div(b.totalLiabilities, b.totalAssets); }, function (v) { return (v * 100).toFixed(1) + '%'; }],
        ['dcd', 'Debtors and creditors days', 'Debtors days and creditors days on one graph', function (b, p, d) { return p.income ? b.ar / p.income * d : null; }, function (v) { return Math.round(v) + ' days'; }]];
      var kid = view === 'kpis' ? opt('k', 'dd') : opt('bm', 'gpm'), kd = K.filter(function (x) { return x[0] === kid; })[0] || K[0], vals = bser(kd[3]);
      var bench = {}; try { bench = JSON.parse(c.inputs.bench || '{}') || {}; } catch (e) { bench = {}; } var bm = view === 'benchmarks' ? bench[kd[0]] : null;
      html = '<div class="xk-card"><h3>' + kd[1] + ending + '</h3><p class="muted">' + (view === 'kpis' ? 'Financial ratios for performance, return, efficiency and leverage. Ratio: ' + pick('k', K.map(function (x) { return [x[0], x[1]]; }), kd[0]) : 'Compare your performance with similar businesses. Metric: ' + pick('bm', K.map(function (x) { return [x[0], x[1]]; }), kd[0])) + '</p><p><strong>Formula:</strong> ' + XK.h(kd[1] + ' = ' + kd[2]) + '</p>' +
        (view === 'benchmarks' && !bm ? '<p>N/A — industry benchmarks are not in the Xero API. Tell the agent a benchmark range and its source (e.g. "gross profit margin benchmark 30–40%, ATO small business benchmarks 2024") to add the band.</p>' : '') + (bm && bm.source ? '<p class="muted">Benchmark: ' + XK.h(kd[4](+bm.low) + ' – ' + kd[4](+bm.high)) + ' · source: ' + XK.h(bm.source) + '</p>' : '') + '<div id="vz-ch"></div></div>';
      after.push(function () { XK.line(document.getElementById('vz-ch'), { title: kd[1], labels: labs, fmt: kd[4], series: kd[0] === 'dcd' ? [{ name: 'Debtors days', values: vals }, { name: 'Creditors days', values: bser(K[1][3]) }] : [{ name: kd[1], values: vals }], band: bm ? { low: keys.map(function () { return +bm.low; }), high: keys.map(function () { return +bm.high; }), name: 'Benchmark (' + (bm.source || 'source not given') + ')' } : null }, c); });
      if (view === 'benchmarks') extraChecks.push({ name: 'Benchmark comparison states its source', pass: bm ? !!bm.source : null, detail: bm ? (bm.source || 'No source given') : 'No benchmark provided' });
      extraChecks.push({ name: 'The ratio shows its formula (information)', pass: null, info: true, detail: kd[1] + ' = ' + kd[2] });
    }
    body.innerHTML = tabs + html + (chips ? '<div class="xk-card detail-block">' + chips.map(function (ch) { return '<button type="button" class="xk-chip' + (self._chip === ch[0] ? ' on' : '') + '" data-chip="' + ch[0] + '">' + ch[1] + '</button>'; }).join('') + (self._chip && insight[self._chip] ? '<p id="vz-ins">' + XK.h(insight[self._chip]) + '</p>' : '') + '</div>' : '');
    after.forEach(function (f) { f(); });
    body.querySelectorAll('.xk-tab').forEach(function (b) { b.addEventListener('click', function () { c.change({}, { v: b.getAttribute('data-v') }); }); });
    body.querySelectorAll('select[id^="vz-"]').forEach(function (s) { s.addEventListener('change', function () { c.setOpt(s.id.slice(3), this.value); }); });
    body.querySelectorAll('.xk-chip').forEach(function (b) { b.addEventListener('click', function () { self._chip = self._chip === b.getAttribute('data-chip') ? null : b.getAttribute('data-chip'); c.change({}, {}); }); });
    // Checks
    var pt = D('pnl_total') ? XK.plParts(XK.walk(D('pnl_total'))) : null, has12 = mc && keys.every(function (k) { return mc.idx[k] != null; }), npS = ser(function (p) { return p.np; });
    var checks = [
      { name: 'Xero returned 12 monthly columns (Profit and Loss and Balance Sheet)', pass: !!has12 && (!bw || (bmc && keys.every(function (k) { return bmc.idx[k] != null; }))), detail: (mc ? mc.keys.length : 0) + ' P&L · ' + (bmc ? bmc.keys.length : 0) + ' Balance Sheet columns' },
      { name: 'Every plotted month re-adds to the 12-month Profit and Loss', pass: pt && has12 ? XK.near(XK.sum(npS), pt.np, 0.05) && XK.near(XK.sum(ser(function (p) { return p.income; })), pt.income, 0.05) : null, detail: pt ? money(XK.sum(npS.filter(function (v) { return v != null; }))) + ' vs ' + money(pt.np) + ' net profit' : Em('pnl_total') }
    ].concat(extraChecks);
    this._x = { keys: keys, P: P };
    return { checks: checks, notes: ['Every series is computed from Xero\'s monthly Profit and Loss and Balance Sheet; insights use the figures shown only.'], na: view === 'benchmarks' ? ['Industry benchmark data (not in the Xero API — supplied by you)'] : view === 'accounts' ? ['Top transactions and contacts for an account (they need Xero\'s journals, which this connection is not granted — see them in Xero → Reports → Account Transactions)'] : [], period: '12 months ending ' + XK.asOfLine(end).replace(/^As at /, ''),
      title: 'Visualise — ' + ((this.views || []).filter(function (v) { return v[0] === view; })[0] || ['', ''])[1] };
  },
  excel: function (c) {
    var x = this._x; if (!x) return [];
    var rows = [[{ v: c.company || 'N/A — not in source', s: 'title' }], [{ v: 'Visualise', s: 'bold' }], ['12 months ending ' + XK.monthLabel(x.keys[11])], [], [{ v: 'Month', s: 'bold' }, { v: 'Trading income', s: 'bold' }, { v: 'Total income', s: 'bold' }, { v: 'Cost of sales', s: 'bold' }, { v: 'Operating expenses', s: 'bold' }, { v: 'Total expenses', s: 'bold' }, { v: 'Net profit', s: 'bold' }]]
      .concat(x.keys.map(function (k, i) { var p = x.P[i]; return [XK.monthLabel(k)].concat(p ? [p.trading, p.income, p.cos, p.opex, p.expenses, p.np].map(function (v) { return { v: v, s: 'money' }; }) : []); }));
    return [{ name: 'Visualise', rows: rows, widths: [14, 16, 16, 16, 18, 16, 16] }];
  }
});
